README.rst
No need for the disclaimer anymore.
=> doc: README: Remove outdated disclaimer

nfc/CHANGELOG.rst
Updated changelog with version 0.3.0 of the NFC libraries.
@kapi-no  could you please review?
=> nfc: Update changelog for Developer 4 release.

crypto/nrf_cc310_mbedcrypto/lib/license.txt, crypto/nrf_cc310_mbedcrypto/license.txt
Signed-off-by: Torsten Rasmussen <torsten.rasmussen@nordicsemi.no>
=> license: Added license.txt for cc310 mbedcrypto libraries

crypto/doc/api.rst, crypto/nrf_cc310_platform/include/nrf_cc310_platform_entropy.h, nrf_security/Kconfig, nrf_security/doc/nrf_security.rst
This commit documents the advanced configuration section in nRF
Security.
=> nrf_security: Updated documentation for nRF Security module

crypto/nrf_cc310_platform/CHANGELOG.rst
-Added changlog text
-Ref: NCSDK-3721
=> crypto: Adding missing nrf_cc310_platform changelog for v0.9.1

bsdlib/README.rst, bsdlib/doc/extensions.rst, bsdlib/doc/pdn_extension.rst
Output:
[PDN management.pdf](https://github.com/NordicPlayground/nrfxlib/files/3973671/PDN.management.pdf)
Add doc for BSD socket extensions. As first topic, add information
about PDN management.
=> doc: add documentation for PDN management

bsdlib/doc/api.rst, bsdlib/doc/at_commands.rst, bsdlib/doc/pdn_extension.rst, bsdlib/doc/security_tags.rst, bsdlib/include/bsd_limits.h, bsdlib/include/bsd_os.h, bsdlib/include/bsd_platform.h, bsdlib/include/nrf_errno.h, bsdlib/include/nrf_socket.h
Updated BSDLib documentation so more information
is showing.
Manifest update: https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1864
=> bsdlib: documentation update

nfc/doc/integration_notes.rst
This commit provides aligned NFC Integration documentation.
Signed-off-by: Kamil Gawor <Kamil.Gawor@nordicsemi.no>
=> nfc: Align NFC integration doc

CODEOWNERS, ble_controller/README.rst, ble_controller/doc/api.rst, ble_controller/doc/ble_controller.rst, bsdlib/README.rst, bsdlib/doc/at_commands.rst, bsdlib/doc/extensions.rst, bsdlib/doc/limitations.rst, bsdlib/doc/security_tags.rst, doc/links.txt, doc/shortcuts.txt, nrf_security/doc/nrf_security.rst
Adding links.txt and shortcuts.txt.
This PR needs a PR in the nrf repo for integration - https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/2153
=> Ncsdk 3898 links.txt

bsdlib/doc/api.rst, bsdlib/doc/extensions.rst, bsdlib/doc/gnss_extension.rst, doc/links.txt
Adding GNSS documentation
Manifest update: https://github.com/nrfconnect/sdk-nrf/pull/2313
=> bsdlib: doc: Adding GNSS conceptual documentation

crypto/doc/nrf_oberon.rst, nrf_security/doc/nrf_security.rst
Updates to nrf_oberon (for v3.0.5)
Updates to nrf_security for obeorn backend
Added missing advanced configuration documentation
Ref: NCSDK-5489
=> Nrf oberon v3.0.5 doc

crypto/nrf_cc310_mbedcrypto/CHANGELOG.rst, crypto/nrf_cc310_platform/CHANGELOG.rst
Fix wrong formatting of notes in some of the change logs.
=> doc: fix formatting of note

zboss/README.rst
Matching the wording to what is used in the Zigbee user guide.
=> doc: update wording for ZBOSS documentation

doc/links.txt, doc/shortcuts.txt, nrf_802154_sl/README.rst
Reviewed documentation of the 802154 SL lib.
Signed-off-by: Grzegorz Ferenc <grzegorz.ferenc@nordicsemi.no>
=> doc: review 802154 SL

ble_controller/CHANGELOG.rst, mpsl/CHANGELOG.rst
Adding 1.3.0 headings in Bluetooth LE Controller
and MPSL changelogs.
=> doc: update changelogs for the release

zboss/license.txt
This add a license file to make to clarify license on binary files.
=> zboss: Add license.txt

zboss/README.rst, zboss/doc/zboss_configuration.rst
Modified subsection heading to fix hierachy.
KRKNWK-7142
Signed-off-by: Grzegorz Ferenc <grzegorz.ferenc@nordicsemi.no>
=> docs: zboss: fix page heading

nrf_security/src/backend/nrf5x/entropy_nrf5x.c
mbedtls_hardware_poll was not doing anything but is needed on nrf52833.
Fixed the function for proper random numbers generation.
manifest pr: https://github.com/nrfconnect/sdk-nrf/pull/3025
=> nrf_security: fix random number gen on nrf52833

mpsl/Kconfig, nrf_security/src/mbedtls/mbedtls_heap.c, softdevice_controller/Kconfig
sdk-nrf: https://github.com/nrfconnect/sdk-nrf/pull/2918
=> Upmerge 2020 09 16

softdevice_controller/README.rst, softdevice_controller/doc/softdevice_controller.rst
Two simple diagrams:
1. How to enable the controller.
2. How to put and get data and events.
=> doc: SoftDevice Controller: Add MSC

openthread/README.rst
Added info there are variants depending on stack and crypto.
Described Configuration used to prepeare each variant
Added info how to select stack variants
=> openthread: doc: describe there are multiple libraries for OpenThread

.github/labeler.yml, .github/workflows/labeler.yml
Add the same labeler action that is already present in sdk-nrf.
=> actions: Add a labeler action

crypto/nrf_cc310_mbedcrypto/license.txt, crypto/nrf_cc310_platform/license.txt, crypto/nrf_cc312_mbedcrypto/license.txt, crypto/nrf_cc312_platform/license.txt
-Adding SPDX-License-Identifier and copyright
=> crypto: Added license for nrf_cc3xx_platform/nrf_cc3xx_mbedcrypto

doc/links.txt, mpsl/CHANGELOG.rst, nfc/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst, zboss/CHANGELOG.rst
Change 'Master branch' heading to 'nRF Connect SDK v1.4.0'.
Affected changelogs:
- SoftDevice Controller
- MPSL
- NFC
=> doc: update changelogs for release

doc/links.txt
Updated link to the ZBOSS doc landing page.
Signed-off-by: Grzegorz Ferenc <grzegorz.ferenc@nordicsemi.no>
=> doc: zboss link update

bsdlib/doc/gnss_extension.rst, doc/links.txt
Adding documentation about the low accuracy use case mode in the GPS
module.
Manifest update: https://github.com/nrfconnect/sdk-nrf/pull/3338
=> bsdlib: doc: gps conceptual doc update

.github/workflows/compliance.yml
Add compliance test on GH directly from the Zephyr tree.
=> ci: add workflow for compliance tests

bsdlib/doc/gnss_extension.rst, doc/links.txt
GNSS doc update
[GNSS socket — nrfxlib 1.4.99 documentation.pdf](https://github.com/nrfconnect/sdk-nrfxlib/files/5664579/GNSS.socket.nrfxlib.1.4.99.documentation.pdf)
=> doc: GNSS doc update

.github/workflows/compliance.yml
Align compliance with the one in upstream zephyr, sdk-zephyr and
sdk-nrf.
=> actions: Align compliance with other repos

nrf_802154_sl/CHANGELOG.rst, nrf_802154_sl/README.rst
Updated 15_4SL docs:
* Added doc review of PR 402
* Added clarifications for changes from PR 366
Signed-off-by: Francesco Servidio <francesco.servidio@nordicsemi.no>
=> doc: Update 15_4SL docs

crypto/nrf_oberon/CHANGELOG.rst
=> doc: bugfix in oberon changelog

nrf_802154_sl/README.rst
Removed sections to leave subpages.
Small edits to the text.
Signed-off-by: Francesco Servidio <francesco.servidio@nordicsemi.no>
=> doc: small fix 15_4SL

crypto/README.rst, mpsl/README.rst, nfc/README.rst, softdevice_controller/README.rst, zboss/README.rst
Move changelogs in the navigation
=> doc: Move changelogs in the navigation

crypto/nrf_oberon/include/ocrypto_chacha20.h, crypto/nrf_oberon/include/ocrypto_chacha20_poly1305.h, crypto/nrf_oberon/include/ocrypto_chacha20_poly1305_inc.h, crypto/nrf_oberon/include/ocrypto_hkdf_sha1.h, crypto/nrf_oberon/include/ocrypto_hkdf_sha256.h, crypto/nrf_oberon/include/ocrypto_hkdf_sha512.h, crypto/nrf_oberon/include/ocrypto_hmac_sha1.h, crypto/nrf_oberon/include/ocrypto_hmac_sha256.h, crypto/nrf_oberon/include/ocrypto_hmac_sha512.h, crypto/nrf_oberon/include/ocrypto_poly1305.h, doc/links.txt, mpsl/doc/fem.rst, mpsl/doc/mpsl.rst, nrf_modem/doc/architecture.rst, nrf_modem/doc/full-dfu.rst, nrf_modem/doc/tls_dtls_configuration.rst, nrf_rpc/doc/usage.rst, nrf_security/doc/backends.rst, softdevice_controller/include/sdc_hci_cmd_le.h, zboss/doc/zboss_configuration.rst
Check and fix the docs for the release - see the separate commits.
=> doc: check docs for release

crypto/nrf_cc310_mbedcrypto/CHANGELOG.rst, crypto/nrf_cc310_platform/CHANGELOG.rst, mpsl/CHANGELOG.rst, nfc/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst
Changed Master branch heading to nRF Connect SDK 1.5.0
Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>
=> doc: update changelogs for release 1.5.0

.checkpatch.conf
Line length rule should be common across all NCS repositories owned by Nordic
=> ci: checkpatch: align line length rule

nrf_modem/include/nrf_socket.h
=> doc: Fix API doc issue in nrf_socket.h

crypto/CMakeLists.txt, crypto/nrf_cc310_platform/src/nrf_cc3xx_platform_mutex_zephyr.c, crypto/nrf_cc310_platform/src/nrf_cc3xx_platform_no_mutex_zephyr.c, crypto/nrf_cc312_platform/src/nrf_cc3xx_platform_mutex_zephyr.c, crypto/nrf_cc312_platform/src/nrf_cc3xx_platform_no_mutex_zephyr.c, nrf_802154/serialization/include/host/nrf_802154.h, nrf_802154/serialization/src/include/nrf_802154_spinel_datatypes.h, nrf_802154/serialization/src/include/nrf_802154_spinel_dec_app.h, nrf_802154/serialization/src/nrf_802154_spinel_app.c, nrf_802154/serialization/src/nrf_802154_spinel_dec_app.c, nrf_802154/serialization/src/nrf_802154_spinel_dec_net.c
builk pr for the 12V2021 upmerge
includes:
#467 
#468
=> For upmerge 12.05.2021

nrf_modem/include/nrf_socket.h
fix API doc issue for nrf_setdnsaddr() in nrf_socket.h
=> doc: fix API doc issue for nrf_setdnsaddr()

nrf_802154/driver/include/nrf_802154_const.h, nrf_802154/driver/src/nrf_802154_encrypt.c, nrf_802154/driver/src/nrf_802154_trx.c, nrf_security/Kconfig, nrf_security/cmake/kconfig_mbedtls_configure.cmake, nrf_security/doc/configuration.rst
#499 #497 #495 #502
sdk-nrf: https://github.com/nrfconnect/sdk-nrf/pull/4873
=> Combine 499 497 495 502

nrf_802154/doc/feature_description.rst
The documentation was updated to reflect the state of the
nRF 802154 Radio Driver.
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>
=> nrf_802154: update doc to reflect current state

nfc/CHANGELOG.rst, nrf_802154/doc/CHANGELOG.rst, zboss/CHANGELOG.rst
ref: NCSDK-8843
Changed Master branch heading to nRF Connect SDK 1.6.0
=> doc: Update changelogs for NCS 1.6.0

doc/links.txt
Edited the order of links in links.txt to match sdk-nrf.
=> doc: reorder links by URL

crypto/nrf_cc310_mbedcrypto/CHANGELOG.rst, crypto/nrf_cc310_platform/CHANGELOG.rst, softdevice_controller/README.rst
Remove occurences of 'please' from NCS docs
ref: NCSDK-9787
=> doc: doc fixes related to NCSDK-9787

crypto/doc/nrf_cc310_mbedcrypto.rst, crypto/doc/nrf_oberon.rst, crypto/nrf_cc310_mbedcrypto/CHANGELOG.rst, crypto/nrf_cc310_platform/CHANGELOG.rst, crypto/nrf_oberon/CHANGELOG.rst, doc/links.txt, nrf_security/README.rst, nrf_security/doc/adv_backend_config.rst, nrf_security/doc/api.rst, nrf_security/doc/backend_config.rst, nrf_security/doc/backends.rst, nrf_security/doc/configuration.rst, nrf_security/doc/glue_layer.rst, nrf_security/doc/mbed_tls_header.rst, nrf_security/doc/prerequisites.rst
=> doc: change mbed TLS to Mbed TLS

nrf_802154/driver/src/mac_features/nrf_802154_frame_parser.c, nrf_802154/driver/src/nrf_802154_trx.c, nrf_802154/serialization/include/host/nrf_802154.h, nrf_802154/serialization/include/host/nrf_802154_types.h, nrf_802154/serialization/src/include/nrf_802154_spinel_datatypes.h, nrf_802154/serialization/src/include/nrf_802154_spinel_dec_app.h, nrf_802154/serialization/src/nrf_802154_spinel_app.c, nrf_802154/serialization/src/nrf_802154_spinel_dec_app.c, nrf_802154/serialization/src/nrf_802154_spinel_dec_net.c
General update of IEEE 802.15.4 radio driver.
sdk-nrf-802154 commit: acf687e5a735494173bc93107d8c4bc8e45ed89f
Signed-off-by: Rafał Kuźnia <rafal.kuznia@nordicsemi.no>
=> nrf_802154: Update the IEEE 802.15.4 component

nrf_802154/driver/src/mac_features/nrf_802154_ifs.c, nrf_802154/driver/src/nrf_802154_core.c
This PR updates revision of the nrf_802154 component to commit
19db7cacff691f3d331473c69432ada969a30697 of the sdk-nrf-802154
repository.
=> nrf_802154: Update revision of nrf_802154

nrf_modem/doc/gnss_interface.rst
Add labels for sections in GNSS interface documentation
for linking purposes and a minor fix.
=> doc improvement: add labels for sections in GNSS interface

zboss/include/addons/zboss_api_af_addons.h, zboss/include/addons/zcl/zb_zcl_identify_addons.h
Fix doxygen issues in ZBOSS addons.
Signed-off-by: Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>
=> zboss: addons: Fix doxygen issues

nrf_modem/doc/tls_dtls_configuration.rst
Ref. NCSDK-11304
Signed-off-by: Richard McCrae <richard.mccrae@nordicsemi.no>
=> doc: Update NRF_SOL_TLS to NRF_SOL_SECURE

nrf_802154/doc/CHANGELOG.rst
NCSDK-11065
Fix RST error in nrf_802154/doc/CHANGELOG
=> doc: Fix RST error in nrf_802154/doc/CHANGELOG

nrf_modem/doc/CHANGELOG.rst, nrf_modem/include/nrf_modem_gnss.h
* Fixed a bug in nrf_send() which could result in the function
incorrectly returning -1 and setting the errno to NRF_EINPROGRESS.
Signed-off-by: Andreas Moltumyr <andreas.moltumyr@nordicsemi.no>
=> nrf_modem: version 1.4.1

mpsl/CHANGELOG.rst, nfc/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst, zboss/CHANGELOG.rst
Update respective changelog files with v1.5.2 release information.
=> doc: Update changelogs for v1.5.2 release

crypto/doc/nrf_cc310_bl.rst, crypto/nrf_cc310_mbedcrypto/include/mbedtls_extra/cc_kdf.h, crypto/nrf_cc310_platform/CHANGELOG.rst, crypto/nrf_cc312_mbedcrypto/include/mbedtls_extra/cc_kdf.h, gzll/include/nrf_gzll.h, openthread/include/openthread/platform/radio.h
Fixed spelling errors
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>
=> nrfxlib: Fixed spelling errors

nrf_security/Kconfig
=> crypto: disable builtin

CODEOWNERS
CODEOWNERS: update openthread codeowners
=> CODEOWNERS: update openthread codeowners

README.rst
Align the nrfxlib contents in alphabetical
order.
Signed-off-by: divya pillai <divya.pillai@nordicsemi.no>
=> doc: Align nrfxlib contents

nrf_802154/doc/CHANGELOG.rst
Changelog related to nrf-802154 part of nrfxlib
=> doc: nrf_802154: update changelog for NCS 1.9.0

nrf_modem/doc/CHANGELOG.rst, nrf_modem/include/nrf_errno.h, nrf_modem/include/nrf_modem.h, nrf_modem/include/nrf_modem_os.h
* Added `nrf_modem_os_trace_irq_enable` and `nrf_modem_os_trace_irq_disable` functions.
* Added support for calling  from a thread.
=> nrf_modem: v1.5.2

doc/links.txt, zboss/doc/zboss_certification.rst
Added sections and links to comp matrices.
KRKNWK-12936.
=> doc: zigbee: update zigbee certification doc page

.github/test-spec.yml
Signed-off-by: dapr <dawid.przybylo@nordicsemi.no>
=> CI: Include softdevice_controller and nrf_802154 for CI-rs-test

.github/test-spec.yml
Adding test spec entries for mesh
Signed-off-by: Alperen Sener <alperen.sener@nordicsemi.no>
=> mesh: add entries

nrf_modem/Kconfig
Add a Kconfig menu for nrf_modem.
Signed-off-by: Emanuele Di Santo <emdi@nordicsemi.no>
=> nrf_modem: update Kconfig

doc/links.txt
Add link to Appropriate Language Mapping Table
Signed-off-by: Azizah Ibrahim <azizah.ibrahim@nordicsemi.no>
=> doc: add reference link

nrf_security/src/legacy/entropy_poll.c
Branch contains changes required for the nrfxlib to work with latest sdk-zephyr upmerge.
=> Upmerge branch 2022-04-19

nrf_modem/README.rst, nrf_modem/doc/CHANGELOG.rst, nrf_modem/doc/api.rst, nrf_modem/doc/fault_handling.rst, nrf_modem/doc/ug_nrf_modem_porting_os.rst, nrf_modem/include/nrf_modem.h, nrf_modem/include/nrf_modem_at.h, nrf_modem/include/nrf_modem_delta_dfu.h, nrf_modem/include/nrf_modem_gnss.h, nrf_modem/include/nrf_modem_limits.h, nrf_modem/include/nrf_modem_os.h, nrf_modem/include/nrf_modem_platform.h, nrf_modem/include/nrf_socket.h, nrf_modem/license.txt
Major release of nrf_modem; highlights:
- Improvements to networking sockets.
Too many to list exhaustively; focused on increasing POSIX compliance,
improving multi-threading support and maintainability.
- Improvements to modem fault handling.
Both detection and recoverability of modem faults have been improved.
=> nrf_modem: v2.0.0

nrf_802154/doc/CHANGELOG.rst
Changelog for the nRF 802.15.4 Radio Driver.
Signed-off-by: Andrzej Kuros <andrzej.kuros@nordicsemi.no>
=> doc: nrf_802154: changelog for v2.0.0

nrf_modem/doc/CHANGELOG.rst
* Corrected the ABI for the hard-float binary.
Signed-off-by: Eivind Jølsgard <eivind.jolsgard@nordicsemi.no>
=> nrf_modem: version 2.0.1+b1

nfc/CHANGELOG.rst, nrf_modem/doc/ug_nrf_modem_porting_os.rst, nrf_security/doc/backend_config.rst, nrf_security/doc/drivers.rst
Minor document fixes on the following
documents:
nfc/CHANGELOG.rst
nrf_modem/doc/ug_nrf_modem_porting_os.rst
nrf_security/doc/backend_config.rst
nrf_security/doc/drivers.rst
Signed-off-by: divya pillai <divya.pillai@nordicsemi.no>
=> doc: Minor document fixes

nrf_modem/doc/ug_nrf_modem_porting_os.rst
Add requirement note for semaphores
Improve IPC interrupt docs
Update implementation template
Signed-off-by: Fabian Nawratil <fabian.nawratil@nordicsemi.no>
=> nrf_modem: doc: Improve OS porting documentation

mpsl/doc/fem.rst
Updated fem.rst
Signed-off-by: Francesco Domenico Servidio <francesco.servidio@nordicsemi.no>
=> doc: FEM feature doc update.

nrf_rpc/CHANGELOG.rst, nrf_rpc/README.rst
This adds CHANGELOG.rst file.
The file contains the changes that have been made
since the library was released.
=> nrf_rpc: Add changelog file.

mpsl/doc/api.rst
Change introduces MPSL FEM power model API documentation.
=> mpsl: doc: Add MPSL FEM power model API documentation

.github/test-spec.yml
Signed-off-by: Dawid Przybyło <dawid.przybylo@nordicsemi.no>
=> test-spec: fem: add label CI-fem-test

.github/test-spec.yml
Signed-off-by: Michał Szablowski <michal.szablowski@nordicsemi.no>
=> test-spec: matter: update files in CI-matter-test

nrf_dm/README.rst, nrf_dm/doc/nrf_dm_usage.rst, nrf_dm/include/nrf_dm.h, nrf_security/README.rst, nrf_security/doc/api.rst, nrf_security/doc/backend_config.rst, nrf_security/doc/driver_config.rst, nrf_security/doc/drivers.rst, nrf_security/doc/mbed_tls_header.rst
Mostly rewording and formatting.
Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>
=> doc improvement: doc fixes for NCS 2.2.0 release

gzll/CHANGELOG.rst, lc3/CHANGELOG.rst, mpsl/CHANGELOG.rst, nrf_dm/doc/CHANGELOG.rst, nrf_rpc/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst
Update changelog versions for 2.2.0 release
Signed-off-by: UMA PRASEEDA <uma.praseeda@nordicsemi.no>
=> doc: Update versions for 2.2.0 release

nrf_modem/doc/fault_handling.rst, nrf_modem/doc/modem_trace.rst
Small updates to the documentation.
Signed-off-by: Emanuele Di Santo <emdi@nordicsemi.no>
=> doc: nrf_modem: small updates

.github/workflows/compliance.yml
=> workflow: compliance: add lxml

nrf_security/doc/driver_config.rst
Typo fix
Signed-off-by: UMA PRASEEDA <uma.praseeda@nordicsemi.no>
=> doc: Typo fix

nrf_modem/doc/at_interface.rst, nrf_modem/doc/sockets.rst
Add section on how to handle PDN-related errors in networking sockets.
=> doc: nrf_modem: add section about PDN-related error handling

nrf_modem/doc/gnss_interface.rst
Improved documentation for how to determine the current GNSS assistance data need.
Improved documentation for reference altitude usage.
NCSDK-12900
=> doc: nrf_modem: improve GNSS interface assistance doc

.github/workflows/compliance.yml
=> workflow: compliance: Fix for 1.9-branch

nrf_modem/doc/gnss_interface.rst
Added a label for GNSS A-GPS data need section.
=> nrf_modem: doc: Add label for GNSS A-GPS data need

crypto/nrf_cc310_mbedcrypto/CHANGELOG.rst, crypto/nrf_cc310_platform/CHANGELOG.rst, crypto/nrf_oberon/CHANGELOG.rst
Fixed mostly the formatting of crypto
changelogs.
=> doc: fixes to crypto libraries’ changelogs

mpsl/CHANGELOG.rst, nrf_fuel_gauge/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst
Updated changelog versions for the NCS 2.4.0 release
=> doc: update versions for 2.4.0 release

.github/test-spec.yml
CI does not need to run on changes to docs only. Updated the test-spec to reflect that.
=> Test spec ignore doc change

.github/test-spec.yml
Trigger Sidewalk tests on changes in crypto and softdevice
=> test_spec: Add Sidewalk

nrf_modem/doc/gnss_interface.rst
Aligned a note in the GNSS 1PPS documentation with the Product Specification.
=> nrf_modem: doc: Update GNSS 1PPS documentation

nrf_modem/doc/gnss_interface.rst
Aligned a note with the Product Specification.
=> doc improvement: doc fix for NCS 2.5.0 release

nrf_modem/doc/CHANGELOG.rst
Added better description of A-GNSS related GNSS API changes to nrf_modem changelog.
=> doc improvement: Add GNSS API changes to nrf_modem changelog

mpsl/CHANGELOG.rst, nrf_802154/doc/CHANGELOG.rst, nrf_rpc/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst
Update doc versions in nrfxlib for 2.5.0
=> doc: Update doc versions in nrfxlib for 2.5.0

nrf_modem/doc/gnss_interface.rst
Improved scheduled download and 1PPS documentation.
=> doc: gnss_interface: Improve GNSS documentation

nrf_wifi/fw_if/umac_if/src/default/fmac_api.c, nrf_wifi/fw_if/umac_if/src/event.c, nrf_wifi/fw_if/umac_if/src/fmac_peer.c
=> wifi: Basic AP mode support

nrf_dm/Kconfig
=> Upmerge 20231010

nrf_wifi/fw_if/umac_if/inc/default/fmac_api.h, nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h, nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h, nrf_wifi/fw_if/umac_if/inc/fmac_util.h, nrf_wifi/fw_if/umac_if/src/default/fmac_api.c, nrf_wifi/fw_if/umac_if/src/event.c, nrf_wifi/fw_if/umac_if/src/fmac_api_common.c, nrf_wifi/fw_if/umac_if/src/fmac_util.c
Remove RAW tx config check for setting mode. Also, remove a redundant declaration in fmac_util.h
=> Remove raw tx config check for mode

nrf_wifi/fw_if/umac_if/src/event.c
Bring in Mode event under SYSTEM mode flag
=> nrf_wifi: Move Mode event under CONFIG_NRF700X_SYSTEM_MODE flag

doc/links.txt, nrf_modem/doc/modem_trace.rst, nrf_modem/doc/sockets.rst, nrf_modem/doc/softsim_interface.rst
Update links of AT Command Reference Guide
=> doc: Update links of AT Command Reference Guide

nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h, nrf_wifi/fw_if/umac_if/src/event.c, nrf_wifi/fw_if/umac_if/src/fmac_util.c, nrf_wifi/fw_if/umac_if/src/rx.c
This set of changes adds Promiscuous mode support to nrf_wifi
=> nrf_wifi: Add Promiscuous mode support

crypto/doc/api.rst, crypto/doc/nrf_cc310_bl.rst, crypto/doc/nrf_cc3xx_mbedcrypto.rst, crypto/nrf_cc310_mbedcrypto/include/mbedtls/cc3xx_kmu.h, crypto/nrf_cc310_platform/include/nrf_cc3xx_platform.h, crypto/nrf_cc310_platform/include/nrf_cc3xx_platform_ctr_drbg.h, crypto/nrf_cc312_mbedcrypto/include/mbedtls/cc3xx_kmu.h, crypto/nrf_cc312_platform/include/nrf_cc3xx_platform.h, crypto/nrf_cc312_platform/include/nrf_cc3xx_platform_ctr_drbg.h, crypto/nrf_oberon/include/ocrypto_constant_time.h, gzll/include/nrf_gzll.h, mpsl/fem/include/protocol/mpsl_fem_protocol_api.h, mpsl/include/mpsl_clock.h, mpsl/include/mpsl_tx_power.h, nfc/CHANGELOG.rst, nrf_802154/doc/wifi_coex_module.rst, nrf_802154/driver/src/nrf_802154_trx_ppi_api.h, nrf_802154/serialization/spinel_base/spinel.h, nrf_802154/sl/sl_opensource/include/mpsl_tx_power.h, nrf_802154/sl/sl_opensource/include/protocol/mpsl_fem_protocol_api.h, nrf_modem/doc/sockets/socket_options_func.rst, nrf_modem/doc/ug_nrf_modem_porting_os.rst, nrf_modem/include/nrf_modem_gnss.h, nrf_rpc/CHANGELOG.rst, nrf_rpc/doc/usage.rst, nrf_wifi/fw_if/umac_if/inc/default/fmac_api.h, nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h, nrf_wifi/fw_if/umac_if/inc/radio_test/fmac_structs.h, nrf_wifi/os_if/inc/osal_api.h, softdevice_controller/include/sdc_hci_vs.h
Documentation fixes
NCSDK-25854
=> doc: Documentation fixes

.github/workflows/backport.yml
18.04 is deprecated, update to 20.04.
=> actions: backport: Update ubuntu version

mpsl/CHANGELOG.rst, nfc/CHANGELOG.rst, nrf_fuel_gauge/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst, softdevice_controller/doc/isochronous_channels.rst
Update doc versions in nrfxlib for 2.6.0
=> doc: Update doc versions in nrfxlib for 2.6.0

.github/workflows/manifest-PR.yml
nordicbuilder workflow was refactored to action. It was also moved to nrfconnect org.
=> ci: use refactored action in manifest-PR.yml

CODEOWNERS
Update codeowners to reflect the current assignment of responsibilities.
=> CODEOWNERS: update codeowners

nrf_802154/driver/src/nrf_802154_aes_ccm_acc_ccm.c
This PR updates revision of the nrf_802154 component to commit
1d4fd62bcad0dad2a1e9f3aee27d669c6a2f5a8b of the sdk-nrf-802154
repository.
=> Update revision of nrf_802154

nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h, nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
TX power ceiling values are now minimum of Board and Chip dependent values.
=> nrf_wifi: Modifications to TX power ceilings in RF params

doc/links.txt, nrf_802154/doc/CHANGELOG.rst, openthread/README.rst
Update the Infocenter links and mentions
with Techdocs
=> doc: update Infocenter links with Techdocs

nrf_modem/include/nrf_modem_dect_phy.h, nrf_rpc/doc/protocol_specification.rst, softdevice_controller/CHANGELOG.rst, softdevice_controller/doc/isochronous_channels.rst, softdevice_controller/include/sdc_hci_vs.h
NCSDK-27762 : Doc check and fixes for 2.7
Link check + toc check
=> doc: Doc check and fixes for 2.7

mpsl/CHANGELOG.rst, nfc/CHANGELOG.rst, nrf_802154/doc/CHANGELOG.rst, nrf_modem/doc/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst, zboss/CHANGELOG.rst
Update doc versions in nrfxlib for v2.7.0
=> doc: update changelogs for v2.7.0

nrf_modem/Kconfig
=> nrf_modem: let DECT PHY be experimental

.github/test-spec.yml
=> test: Fix tests trigger

openthread/CMakeLists.txt, openthread/cmake/extensions.cmake
Fix paths for MbedTLS configurations.
=> openthread: fix MbedTLS paths

nrf_rpc/nrf_rpc.c
Backport 6abe6905b336503fc48f960e4e02e335f359d685 from #1548.
=> [Backport v2.8-branch] nrf_rpc: fix error handling

nrf_802154/driver/src/nrf_802154_trx.c
Backport f13590276da0cf735b9d4522fec8c428e7bef9d4 from #1554.
=> [Backport v2.8-branch] Update revision of nrf_802154

doc/links.txt, mpsl/CHANGELOG.rst, nrf_802154/doc/CHANGELOG.rst, nrf_fuel_gauge/CHANGELOG.rst, nrf_modem/doc/CHANGELOG.rst, nrf_rpc/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst
Updated doc versions in nrfxlib for 2.8.0
=> doc: Update doc versions in nrfxlib for 2.8.0

nrf_802154/doc/CHANGELOG.rst, nrf_modem/doc/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst
Updated doc versions in nrfxlib for 2.9.0
NCSDK-30704
=> doc: Update doc versions in nrfxlib for 2.9.0

.github/workflows/compliance.yml
Backport 40564fa1b63cc275daf04c4cbf61b8ec7232d35d from #1624.
=> [Backport v2.9-branch] ci: fix compliance by using ubuntu-22.04

.github/test-spec.yml
=> test: CI-ps-test in test-spec.yml

nrf_modem/doc/softsim_interface.rst
=> nrf_modem: doc: softsim_interface: fix typo

.github/workflows/compliance.yml
Trying to fix compliance workflow.  manifest-pr-skip
=> ci: fix compliance workflow

.github/workflows/stale.yml
This will ensure we reduce the list of old abandoned PRs.
=> actions: Add stale action to nrfxlib

.github/workflows/backport.yml, .github/workflows/compliance.yml, .github/workflows/labeler.yml, .github/workflows/stale.yml
=> ci: Pin GH actions to SHAs

nrf_rpc/nrf_rpc.c
Fix one missed scenario in which transport_initialized flag may be false because of the thread running nrf_rpc_init() being switched out by the scheduler before setting this flag.
In such a case, if there's an init packet received, responding to this packet might trigger an error.
=> nrf_rpc: fix another case where transport_initialized is false

crypto/doc/CHANGELOG_oberon.rst, doc/links.txt, nfc/doc/type_2_tag.rst, nrf_fuel_gauge/CHANGELOG.rst, nrf_modem/doc/dectphy.rst
Documentation fixes for 3.0.0
NCSDK-32646
=> doc: Documentation fixes for 3.0.0

crypto/doc/CHANGELOG_oberon.rst, doc/links.txt, nfc/doc/type_2_tag.rst, nrf_fuel_gauge/CHANGELOG.rst, nrf_modem/doc/dectphy.rst
Backport 08eea6edf8b6770a368c5f40b0dc02807d390b61 from #1703.
=> [Backport v3.0-branch] doc: Documentation fixes for 3.0.0

nfc/CHANGELOG.rst, nrf_802154/doc/CHANGELOG.rst, nrf_fuel_gauge/CHANGELOG.rst, nrf_modem/doc/CHANGELOG.rst, softperipheral/CHANGELOG.rst
Updated doc versions in nrfxlib for 3.0.0
NCSDK-32648
=> doc: Update doc versions in nrfxlib for 3.0.0

.github/test-spec.yml
=> tests: update test_spec label for E2E DFU tests

mpsl/CHANGELOG.rst, nrf_802154/doc/CHANGELOG.rst, nrf_802154/doc/rd_service_layer_lib.rst, nrf_modem/doc/CHANGELOG.rst, nrf_rpc/CHANGELOG.rst, softdevice_controller/CHANGELOG.rst, softperipheral/doc/sQSPI/features.rst, softperipheral/doc/sQSPI/nrf54H20_porting_v1_1_0.rst, softperipheral/doc/sQSPI/nrf54L15_porting_v1_1_0.rst
Updated doc versions in nrfxlib for 3.1.0
NCSDK-34657
=> doc: Update doc versions in nrfxlib for 3.1.0
