nrfconnect/sdk-nrfxlib

- CMakeLists.txt
- ble_controller/CMakeLists.txt
- bsdlib/CMakeLists.txt
- common.cmake
- crypto/CMakeLists.txt
- nfc/CMakeLists.txt
Support having a 'nrfxlib' directory present without having
'GCC_M_CPU'. As the build scripts were written before, nrfxlib build
scripts would run code that was not relevant to builds that did not
actually use any nrfxlib components.
This has been resolved by moving code from the root
'nrfxlib/CMakeLists.txt' and into the subdirectories that are only
included when their components are enabled through Kconfig.
This re-organization allows the 'nrfxlib' directory to be present
while doing non-nrfxlib builds, like x86 builds for instance.
The code is now written such that 'nrfxlib' modules include the
relevant common 'nrfxlib' code that they need, as opposed to having
common build script code be executed before 'nrfxlib' modules are
executed.
> cmake: Support sourcing NRFXLIB_DIR without having GCC_M_CPU set

- nfc/doc/api.rst
Typo in the ID of the API file for NFC so that it could not
be linked to. Added more specific IDs as well.
> doc: Fix ID for the NFC API file

- bsdlib/include/nrf_socket.h
This is to align with standard name POLLNVAL.
Signed-off-by: Stig Bjørlykke <stig.bjorlykke@nordicsemi.no>
> bsdlib: Rename NRF_POLLINVAL to NRF_POLLNVAL

- bsdlib/include/nrf_socket.h
Implementation in bsdlib will come in a later update of the lib.
Signed-off-by: Stig Bjørlykke <stig.bjorlykke@nordicsemi.no>
> bsdlib: Add NRF_SO_ERROR and NRF_SO_BINDTODEVICE

- ble_controller/Kconfig
Add a dependency from BT_LL_NRFXLIB onto SOC_SERIES_NRF52X to prevent
users from creating invalid configurations. BT_LL_NRFXLIB only runs on
nRF52.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> kconfig: Enforce that BT_LL_NRFXLIB depends on nRF52

- nfc/Kconfig
- nfc/src/nfc_platform_zephyr.c
Fix errors from use of two clock drivers
in the same time.
Signed-off-by: Kamil Gawor <Kamil.Gawor@nordicsemi.no>
> nfc: Fix nfc platform clock assert

- bsdlib/include/nrf_errno.h
Documentation build throw warning because of this.
> bsdlib: Define missing nrf_errno doxygen group

- CMakeLists.txt
- zephyr/module.yml
In order to include the repository in the Zephyr build, we used to rely
on a custom hook in the zephyr repository's root CMakeLists.txt and
Kconfig.zephyr files, which included the nrf/ repository and this in
turn included the present nrfxlib/ one. Now that Zephyr natively supports
external modules, use this mechanism to include nrfxlib in the Zephyr build
without relying on the nrf repository.
> build: Switch to using Zephyr modules to include the repo

- crypto/doc/api.rst
This is a showstopper for `nrfxlib` version update in https://github.com/NordicPlayground/fw-nrfconnect-nrf as it triggers CI failure.
`nrf_oberon` group is no longer present, therefore it cannot be referenced.
> nrf_oberon: Remove non-existing doc references

- bsdlib/CMakeLists.txt
- crypto/CMakeLists.txt
This change adds support for building multi-image builds with crypto
interfaces such as cc310 and oberon. This will not break anything for
other builds as `${IMAGE}` will be resolved to ` `.
Signed-off-by: Sigvart Hovland <sigvart.m@gmail.com>
> crypto: cmake: Add support for multi-image build of crypto

- ble_controller/README.rst
Certain toolchains are known to segfault when linking with the
ble_controller library.
It is not known exactly which set of toolchains segfault. It is
believed to affect all NCS revisions as of april 2019.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> doc: ble_controller: Document known toolchain issue

- bsdlib/CHANGELOG.rst
An empty line was missing before the bullet points, messing up the
layout.
> bsdlib: Add missing empty line to the changelog

- bsdlib/CMakeLists.txt
Making liboberon to an imported target.
To ensure the ordering of linking when using both libbsd and liboberon, the bsd lib is now setting oberon as link library interface to ensure oberon will follow during final linking and thus symbols can be correctly resolved.
Signed-off-by: Torsten Rasmussen <torsten.rasmussen@nordicsemi.no>
> libbsd: bsd lib is now an imported target

- nrf_security/cmake/symbol_rename.cmake
- nrf_security/include/mbedcrypto_glue/mbedtls/aes_alt.h
- nrf_security/src/mbedcrypto_glue/CMakeLists.txt
- nrf_security/src/mbedcrypto_glue/cc310/CMakeLists.txt
- nrf_security/src/mbedcrypto_glue/cc310/aes_cc310.c
- nrf_security/src/mbedcrypto_glue/cc310/ccm_cc310.c
- nrf_security/src/mbedcrypto_glue/cc310/rsa_cc310.c
- nrf_security/src/mbedcrypto_glue/ecdsa_alt.c
- nrf_security/src/mbedcrypto_glue/symbol_rename.template.txt
- nrf_security/src/mbedcrypto_glue/vanilla/CMakeLists.txt
- nrf_security/src/mbedcrypto_glue/vanilla/aes_vanilla.c
- nrf_security/src/mbedcrypto_glue/vanilla/ccm_vanilla.c
- nrf_security/src/mbedcrypto_glue/vanilla/cmac_vanilla.c
- nrf_security/src/mbedcrypto_glue/vanilla/dhm_vanilla.c
- nrf_security/src/mbedcrypto_glue/vanilla/ecdh_vanilla.c
- nrf_security/src/mbedcrypto_glue/vanilla/ecdsa_vanilla.c
- nrf_security/src/mbedcrypto_glue/vanilla/rsa_vanilla.c
- nrf_security/src/mbedtls/CMakeLists.txt
To ensure the mbedtls_cipher_* functions from cipher.c is no longer
renamed as those only exists in vanilla mbedTLS.
mbedtls_platform_zeroize will not be renamed for the cc310 if multiple
backends are selected, while other backends will still have their
symbol renamed.
also ensuring correct link ordering and dependencies when linking to
mbedtls then mbedtls is now linked with mbedx509.
Fixed naming of defines and functions in glue layer as there were
mismatch in naming.
Adjust backend libraries to be Zephyr libraries to ensure autoconf.h is
included during compilation.
> Platform zeroize fix - glue symbol naming fix

- crypto/CMakeLists.txt
- nrf_security/cmake/symbol_rename.cmake
- nrf_security/src/mbedcrypto_glue/CMakeLists.txt
- nrf_security/src/mbedcrypto_glue/cc310/CMakeLists.txt
- nrf_security/src/mbedcrypto_glue/vanilla/CMakeLists.txt
- nrf_security/src/mbedtls/CMakeLists.txt
To support nrf security in SPM the CMake files controlling the
crypto and mbedtls libraries no have all target references prefixed
with ${PREFIX}.
> cmake: added ${IMAGE} on all target handling to support multi image

- bsdlib/CMakeLists.txt
Added -lgcc at end of target_link_libraries in
CMakeLists.txt to fix undefined reference to
`__aeabi_uldivmod' when building samples that use bsdlib
and have CONFIG_DEBUG_OPTIMIZATIONS enabled.
Signed-off-by: Ole Sæther <ole.saether@nordicsemi.no>
> bsdlib: Moved bsd library before TOOLCHAIN_LIBS in CMakeLists.txt

- nfc/src/nfc_platform_zephyr.c
With recent DT changes in Zephyr upstream, some DT symbols became
obsolete, which causes warnings during compilation.
> nfc: Update deprecated device tree symbols

- crypto/Kconfig
Not only nRF52840 has CC310.
Signed-off-by: Øyvind Rønningstad <oyvind.ronningstad@nordicsemi.no>
> crypto: cc310_bl: Reword prompt

- bsdlib/license.txt
Add Nordics 5-clause license to bsdlib.
Signed-off-by: Rune Holmgren <Raane.Holm@gmail.com>
> NCSDK-2480: Add Nordics 5-clause license to bsdlib.

- nfc/license.txt
Adding license reference for NFC libraries.
Signed-off-by: Michał Grochala <michal.grochala@nordicsemi.no>
> nfc: add license

- Jenkinsfile
Managing Docker version, Agent Labels, Github Status, manifest updates, downstream jobs from CI_LIB.
More info: https://projecttools.nordicsemi.no/confluence/display/NCS/Linking+Jenkins+Jobs+Together
Signed-off-by: Thomas Stilwell Thomas.Stilwell@nordicsemi.no
> ci: use Standard Library in Jenkinsfile to link sub-projects together

- common.cmake
- crypto/Kconfig
-Added Kconfig option to indicate build with -fshort-wchar
-Updated nrfxlib_caculate_lib_path to also select short-wchar
> Add Kconfig option CONFIG_SHORT_WCHAR_T

- nrf_security/doc/nrf_security.rst
This commit reworks the way that nrf security reference into nrf docs
due to a current limitation in doxygen setup/doc generation.
> nrf_security: Modified references from nrfxlib to nrf

- nfc/Kconfig
Fixes NCSDK-3404 and a small documentation bug.
Signed-off-by: Thomas Stenersen <thomas.stenersen@nordicsemi.no>
> nfc: Fix default IRQ priority when ZERO_LATENCY_IRQS are used

- nrf_security/Kconfig
- nrf_security/src/mbedtls/CMakeLists.txt
- nrf_security/src/mbedtls/mbedtls_heap.c
This commit introduces mbedtls_heap.c in nrf security and also add
globals in compiled libraries to userspace config using
zephyr_library_app_memory.
> nrf_security: introduces mbedtls heap in nrf_security

- ble_controller/Kconfig
Add Kconfig support configuration symbols to BLE controller for so that
dependent configurations can be set from this. This enables features
in the host e.g. PHY update.
> Kconfig: ble_controller: Update to upstream Kconfig support configs.

- bsdlib/README.rst
Incorrect modem limitations stated in bsdlib doc.
> doc: remove wrong modem limitations in bsdlib doc

- bsdlib/README.rst
Incorrect modem limitations stated in bsdlib doc.
> Manual Backport: bsd lib doc update

- nfc/include/nfc_t2t_lib.h
- nfc/include/nfc_t4t_lib.h
Removed outdated and misleading statements in the API documentation.
Fixing: NCSDK-1859
> nfc: T2T library documentation: removed obsolete statements

- mpsl/Kconfig
Select ZERO_LATENCY_IRQS in Kconfig for MPSL library so that the IRQs
can be connected with the IRQ_ZERO_LATENCY flag. When this flag is
used, ISRs cannot be blocked by irq_lock.
Signed-off-by: Solveig Fure <Solveig.Fure@nordicsemi.no>
> mpsl: Enable zero latency IRQs for MPSL

- CODEOWNERS
Add codeowners file to auto-assign reviewers.
> CODEOWNERS: Add codeowners file

- bsdlib/CMakeLists.txt
- crypto/CMakeLists.txt
- nrf_security/CMakeLists.txt
- nrf_security/cmake/symbol_rename.cmake
- nrf_security/src/mbedcrypto_glue/CMakeLists.txt
- nrf_security/src/mbedcrypto_glue/cc310/cc310_glue.cmake
- nrf_security/src/mbedcrypto_glue/vanilla/vanilla_glue.cmake
- nrf_security/src/mbedtls/CMakeLists.txt
All occurrences of ${IMAGE} have been removed in order to adopt to the
new strategy used for multi image builds.
> cmake: Adopted to new multi image approach

- crypto/nrf_cc310_platform/src/nrf_cc310_platform_abort_zephyr.c
The file has been moved from misc/ to power/. Update its inclusion
accordingly.
Signed-off-by: Andrzej Głąbek <andrzej.glabek@nordicsemi.no>
> crypto: cc310: Update path in inclusion of Zephyr's reboot.h

- .github/workflows/backport.yml
- CODEOWNERS
- Jenkinsfile
- nrf/master:HEAD is used by default
- Add common CRON functionality
- update Jenkinsfile for CI_LIB v2
- Add entry to CODEOWNERS
- Add Github-Actions:BackPortBot
Signed-off-by: Thomas Stilwell <Thomas.Stilwell@nordicsemi.no>
> ci: use nRF manifest to get ci-tools repo

- bsdlib/include/nrf_socket.h
nrf_getaddrinfo returns only one address at the moment, not a
list of addresses.
Also clarified what the hint parameter contains.
See https://projecttools.nordicsemi.no/jira/browse/NCSDK-1952.
Note that this function is not displayed in the documentation output. See https://projecttools.nordicsemi.no/jira/browse/NCSIDB-16
> nrf_socket: document limitations of nrf_getaddrinfo

- nrf_security/doc/nrf_security.rst
This commit fixes some outdated information regarding Kconfig of nrf
security docs after refactoring.
> doc: nrf_security configuration documentation fix.

- CODEOWNERS
Transfer CODEOWNER file matches from SebastianBoe to tejlmand as
tejlmand is taking over the build and configuration system code owner
position.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> codeowners: Transfer codeowner files from SebastianBoe to tejlmand

- README.rst
The Kconfig documentation will be shared and in a separate documentation
set once https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/1258
is in.
This commit should be merged together with that PR. It's fine to merge
it slightly after though, because this is just fixing a warning.
> doc: README: Remove kconfig/index from toctree

- nrf_security/Kconfig
- nrf_security/cmake/kconfig_mbedtls_configure.cmake
- nrf_security/configs/nrf-config.h.template
- Adds minor changes postponed after Q1 release
- Enabling HMAC_DRBG as a configurable option in nrf_security
- Allowing mbed TLS AES to be configured to use ROM tables to conserve RAM
> nrf_security: crypto improvements post Q1 release

- nrf_security/src/mbedcrypto_glue/vanilla/aes_vanilla.c
- nrf_security/src/mbedcrypto_glue/vanilla/ccm_vanilla.c
- nrf_security/src/mbedcrypto_glue/vanilla/rsa_vanilla.c
Zephyr replaced BUILD_ASSERT_MSG by BUILD_ASSERT macro.
nedded for the upmereg
https://github.com/NordicPlayground/fw-nrfconnect-nrf/pull/2172
Signed-off-by: Andrzej Puzdrowski <andrzej.puzdrowski@nordicsemi.no>
> nrf_security/src/mbedcrypto_glue/vanilla: fix BUILD_ASSERT_MSG macro

- common.cmake
- crypto/Kconfig
Update FLOAT and FP_SHARING to FPU and FPU_SHARING respectively
renamed upstream.
> kconfig: Update to FPU and FPU_SHARING renamed upstream

- common.cmake
- crypto/Kconfig
This reverts commit a9c1f80636ceeeb678465959986ba831ff4cdf31.
This needs to be merged together with the upmerge.
Reverting, and re-opening original PR, so that other nrfxlib PRs can continue.
> Revert "kconfig: Update to FPU and FPU_SHARING renamed upstream"

- Jenkinsfile
Point to nrfconnect instead of NordicPlayground, the new home of the NCS
repos.
> jenkins: Point to the new nrfconnect org

- nrf_security/cmake/combine_archives.cmake
- nrf_security/cmake/combine_archives_script.cmake
This is a critical fix, solving the dependency issue discovered here: https://github.com/nrfconnect/sdk-nrf/pull/2324#issuecomment-634664486
-----
-Echoing in post-command due to unforseen issues on build server
Issue is unknown in origin but may be cmake/ninja version related
> nrf_security: Fixing dependency issue with file generate (critical / hotfix)

- nrf_security/cmake/symbol_strip.cmake
- nrf_security/src/mbedcrypto_glue/oberon/ccm_oberon.c
nrf_security: Removing deprecated BUILD_ASSERT_MSG and fixing empty_file.c.obj
-Fixing CI issues on ccm_oberon.c
-Fixing issue with empty_file.c.obj in library recombination
> Feature/nrf oberon v3.0.5

- bsdlib/doc/api.rst
Added doxygen group name to api.rst.
Screenshot of output -> 
The problem is that a new doxygen group was added for these values. With our current doxygen-RST integration, all doxygen groups must be explicitly included in RST, even if they are a subgroup.
> doc: fix api doc for bsdlib_init return values

- nrf_802154_sl/include/nrf_802154_sl_config.h
802.15.4 RTC priority was set to 6 what is out of allowed range for
Zephyr in selected configurations. Incrase to priority 5.
Signed-off-by: Hubert Miś <hubert.mis@nordicsemi.no>
> nrf_802154_sl: Increase 802.15.4 RTC IRQ priority

- README.rst
- doc/links.txt
- zboss/README.rst
Adding a page with some description and a link to the ZBOSS API doc.
The API doc is generated from doxygen and uploaded to developer.nordicsemi.com.
Output can be previewed here:
[ZBOSS Zigbee stack — nrfxlib 1.2.99 documentation.pdf](https://github.com/nrfconnect/sdk-nrfxlib/files/4701553/ZBOSS.Zigbee.stack.nrfxlib.1.2.99.documentation.pdf)
The text for the landing page is taken from the old SDK, @wbober @tomchy  please suggest changes, if needed.
> doc: landing page for zboss api doc

- nrf_802154_sl/CHANGELOG.rst
- nrf_802154_sl/include/fem/nrf_fem_control_config.h
- nrf_802154_sl/include/fem/nrf_fem_protocol_api.h
- nrf_802154_sl/include/fem/simple_gpio/nrf_fem_config.h
- nrf_802154_sl/include/fem/three_pin_gpio/nrf_fem_config.h
- nrf_802154_sl/include/nrf_802154_sl_ant_div.h
- nrf_802154_sl/include/nrf_802154_sl_config.h
- nrf_802154_sl/include/nrf_802154_sl_log.h
- nrf_802154_sl/include/nrf_802154_sl_periphs.h
- nrf_802154_sl/include/nrf_802154_sl_stats.h
- nrf_802154_sl/include/nrf_802154_sl_utils.h
- nrf_802154_sl/include/platform/clock/nrf_802154_clock.h
- nrf_802154_sl/include/platform/gpiote/nrf_802154_gpiote.h
- nrf_802154_sl/include/platform/hp_timer/nrf_802154_hp_timer.h
- nrf_802154_sl/include/platform/irq/nrf_802154_irq.h
- nrf_802154_sl/include/platform/lp_timer/nrf_802154_lp_timer.h
- nrf_802154_sl/include/rsch/coex/nrf_802154_wifi_coex.h
- nrf_802154_sl/include/rsch/nrf_802154_rsch.h
- nrf_802154_sl/include/rsch/nrf_802154_rsch_crit_sect.h
- nrf_802154_sl/include/rsch/nrf_802154_rsch_prio_drop.h
- nrf_802154_sl/include/rsch/raal/nrf_raal_api.h
- nrf_802154_sl/include/rsch/raal/nrf_raal_config.h
- nrf_802154_sl/include/timer/nrf_802154_timer_coord.h
- nrf_802154_sl/include/timer/nrf_802154_timer_sched.h
This patch aligns nRF 802.15.4 SL's public API to use the correct
license.
KRKNWK-6298
Signed-off-by: Ciupis, Jedrzej <jedrzej.ciupis@nordicsemi.no>
> nrf_802154_sl: Update nRF 802.15.4 SL to v0.1.2

- doc/links.txt
Build is failing because bsdlib/README.rst is referring to a link which is currently not available in the links.txt file, so add it.
> doc: add missing referenced link

- ble_controller/include/nrf_errno.h
- bsdlib/include/bsd.h
- bsdlib/include/bsd_os.h
- bsdlib/include/bsd_platform.h
- bsdlib/include/nrf_errno.h
- bsdlib/include/nrf_socket.h
- crypto/nrf_cc310_bl/include/nrf_cc310_bl_hash_sha256.h
- crypto/nrf_cc310_platform/include/nrf_cc310_platform.h
- crypto/nrf_cc310_platform/include/nrf_cc310_platform_mutex.h
- nfc/include/nfc_t2t_lib.h
- nfc/include/nfc_t4t_lib.h
This fixes warnings generated by Doxygen, apart from those generated under the `zboss` and `nrf_802154_sl` directories.
> Fix doxygen warnings

- nrf_security/src/backend/nrf5x/entropy_nrf5x.c
- nrf_security/src/mbedtls/CMakeLists.txt
- nrf_security/src/mbedtls/oberon/CMakeLists.txt
- nrf_security/src/mbedtls/shared/CMakeLists.txt
- nrf_security/src/mbedtls/vanilla/CMakeLists.txt
-Fixed if to ensure include only if platform_cc310 is a target
-Standardized on same format in vanilla mbed TLS for platform_cc310
Ref: NCSDK-5706
> nrf_security: Fixing faulty matching platform_cc310

- zboss/include/addons/zcl/zb_zcl_basic_addons.h
Increase string members in `zb_zcl_basic_attrs_ext_t` struct to have enough space
for string length subfield and maximum allowed string subfield
Signed-off-by: Maciej Fabia <maciej.fabia@nordicsemi.no>
> zboss: Increase string members in zb_zcl_basic_attrs_ext_t

- mpsl/Kconfig
- nfc/doc/type_2_tag.rst
- nfc/include/nfc_t2t_lib.h
- nfc/include/nfc_t4t_lib.h
- nrf_security/src/backend/nrf5x/entropy_nrf5x.c
nrf: https://github.com/nrfconnect/sdk-nrf/pull/2585
This is a new Kconfig option introduced in upstream Zephyr in commit
7f66fd84e849dccfd388a4b5a40563829a0f38c6 ("drivers: ieee802154: fix
nrf5 initialization with external irq source"). When enabled, the
zephyr driver does not configure the radio IRQ, so it is required for
use with MPSL.
Signed-off-by: Martí Bolívar <marti.bolivar@nordicsemi.no>
> mpsl: Kconfig: select IEEE802154_NRF5_EXT_IRQ_MGMT

- bsdlib/doc/security_tags.rst
- doc/links.txt
- nfc/README.rst
- nfc/doc/type_2_tag.rst
- nfc/doc/type_4_tag.rst
Remove links to nrf documentation from links.txt file, and add proper link references to be resolved by intersphinx.
JIRA: NCSDK-3934
> doc: use intersphinx to resolve nrf links

- doc/links.txt
Added link to Nordic Infocenter in the links file.
This is going to be referenced by a later update to the documentation
for ble_controller.
Signed-off-by: Frederik Vestre <frederik.vestre@nordicsemi.no>
> doc: Add link to infocenter

- crypto/CMakeLists.txt
- nrf_security/Kconfig
#KRKNWK-6791
Some include files point to the file that was not in the include path.
Added cc310 platform includes to the zephyr include path.
Modified some defaults so the user does not need to worry about setting
them manually to enable OpenThread
> cmake: crypto: nrf_security: Enabling nrf_security for OpenThread

- softdevice_controller/Kconfig
For Bluetooth Mesh use BT_LL_SW_SPLIT.
For all other Bluetooth use cases, use the SoftDevice Controller.
Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>
Manifest update: https://github.com/nrfconnect/sdk-nrf/pull/2769
> softdevice_controller: SoftDevice Controller as the default BLE LL

- bsdlib/doc/gnss_extension.rst
Adding information about the relationship between PVT notifications
and NMEA strings.
Manifest update PR: https://github.com/nrfconnect/sdk-nrf/pull/2793
Signed-of-by: Even Falch-Larsen <even.falch-larsen@nordicsemi.no>
> bsdlib: doc: specify relationship between PVT and NMEA

- nrf_security/CMakeLists.txt
This commit aligns the usage of west to upstream Zephyr, where Python
is used directly to ensure the same python is used for west.
This updates nrfxlib to use same principle as here: https://github.com/zephyrproject-rtos/zephyr/pull/26060
-----
Manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/2781
> cmake: nrf_security: use same python as rest of build system for west

- mpsl/Kconfig
802154 radio driver uses MPSL api to provide multiprotocol support. It seems it is a good place to active this feature.
Corresponding sdk-nrd PR: https://github.com/nrfconnect/sdk-nrf/pull/2766
> mpsl: 802154 multiprotocol support

- openthread/README.rst
Renamed CONFIG_OPENTHREAD_MBEDTLS_TARGET_NAME to
CONFIG_OPENTHREAD_MBEDTLS_LIB_NAME in doc as the option was changed in
upstream.
> doc: openthread: Renamed mbedtls config option

- softdevice_controller/CHANGELOG.rst
For nrf53, NCS is the only option.
Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>
> doc: softdevice_controller: Document that NCS DTM can be used.

- softdevice_controller/CHANGELOG.rst
No underscore is needed.
Signed-off-by: Rubin Gerritsen <rubin.gerritsen@nordicsemi.no>
> softdevice_controller: Fix DTM link

- openthread/CMakeLists.txt
- openthread/cmake/extensions.cmake
With this extension OpenThread libraries will be able to use OpenThread
stack build from source to overwrite the nrfxlib binaries.
Signed-off-by: Piotr Szkotak <piotr.szkotak@nordicsemi.no>
Functionality extracted from: https://github.com/nrfconnect/sdk-nrf/pull/2655
> openthread: Add install_openthread_libraries target

- nrf_security/src/mbedtls/mbedtls_heap.c
Title.
Needed in order to allow successfully testing on nrf52810 and nrf52811 (or other devices with similarly restricted FLASH/SRAM).
> nrf_security: Allow reallocating mbedtls heap

- nrf_security/src/mbedtls/CMakeLists.txt
nrf_security does not build when softdevice controller is enabled.
Softdevice controller uses separate entropy driver based on RNG peripheral.
This commit allows to use NRF5 RNG backend with softdevice entropy driver.
> nrf_security: Enable NRF5 entropy backend for softdevice entropy driver

- README.rst
- bsdlib/README.rst
- bsdlib/doc/extensions.rst
- crypto/README.rst
- mpsl/README.rst
- nfc/README.rst
- nrf_rpc/README.rst
- nrf_rpc/doc/api.rst
- nrf_security/README.rst
- softdevice_controller/README.rst
Make sure links to subpages are at the bottom of the page
and have a "Subpages:" heading.
Also, fix the order of libraries in the doc to be alphabetical.
Ref. NCSDK-6532
> doc: clean up links to subpages

- nrf_security/src/backend/nrf5x/entropy_nrf5x.c
On latest zephyr upmerge consts were added to devices, however this file
was skipped.
> nrf_security: fix warning when building nrf52833

- crypto/doc/nrf_cc310_mbedcrypto.rst
- crypto/doc/nrf_oberon.rst
- nrf_security/README.rst
- nrf_security/doc/adv_backend_config.rst
- nrf_security/doc/api.rst
- nrf_security/doc/backend_config.rst
- nrf_security/doc/backends.rst
- nrf_security/doc/configuration.rst
- nrf_security/doc/glue_layer.rst
- nrf_security/doc/mbed_tls_header.rst
- nrf_security/doc/prerequisites.rst
Splitting the one huge RST file into smaller ones.
This should help in maintaining this doc in the future.
Fixing a lot of links that got broken due to structure change.
Also, some small general fixes.
> doc: Rework of nrf_security doc

- nrf_security/Kconfig
- nrf_security/doc/api.rst
- nrf_security/doc/backend_config.rst
- nrf_security/src/mbedcrypto_glue/CMakeLists.txt
- nrf_security/src/mbedcrypto_glue/cc310/cc310_glue.cmake
- nrf_security/src/mbedcrypto_glue/oberon/oberon_glue.cmake
- nrf_security/src/mbedcrypto_glue/vanilla/vanilla_glue.cmake
-Disabling CMAC glue in nrf_security due to memory complexities
-Changed CMAC: "Glue" => "Choice" (single backend enabled)
-Added CHOICE_XXXX_MBEDTLS_CMAC_C for backend selection in Kconfig
-Updated documentation for CMAC: "Glue" => "Choice"
manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/3122
ref: NCSDK-5883
> nrf_security: Disabling CMAC gluing

- doc/links.txt
Point to a common landing page on developer.nordicsemi.com
that contains links to different ZBOSS versions.
> doc: change zboss api doc link

- openthread/license.txt
This commit adds missing licensing for provided OpenThread binary files.
Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>
KRKNWK-7955
Pulled by https://github.com/nrfconnect/sdk-nrf/pull/3252
> openthread: add license for binary files

- mpsl/Kconfig
- softdevice_controller/Kconfig
Manifest update: https://github.com/nrfconnect/sdk-nrf/pull/3294
> MPSL and SDC on nrf53 can only run on the network core

- bsdlib/doc/api.rst
A link between a new doxygen group in the bsdlib header file and
a api.rst restructured text file was missing. So this group doesn̈́'t
appear in the public documentation online.
Manifest update: https://github.com/nrfconnect/sdk-nrf/pull/3288
> bsdlib: doc: added missing link between doxygen section and sphinx

- nrf_security/cmake/combine_archives.cmake
- nrf_security/cmake/combine_archives_script.cmake
- nrf_security/cmake/symbol_rename.cmake
- nrf_security/cmake/symbol_strip.cmake
- nrf_security/src/mbedcrypto_glue/CMakeLists.txt
- nrf_security/src/mbedtls/cc310/CMakeLists.txt
- nrf_security/src/mbedtls/oberon/CMakeLists.txt
Headlines in this PR:
Using custom target for combined backend libraries
- Removes empty_file.c
- Remove need for POST_BUILD
Changing list into individual CMake arguments when combining libraries
- Fixes issues with quoting of lists
CMake code cleanup
--------
Manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/3298
> Nrf security cmake archiving fixes

- bsdlib/include/nrf_socket.h
- crypto/nrf_cc310_platform/include/nrf_cc310_platform.h
- crypto/nrf_cc310_platform/include/nrf_cc310_platform_abort.h
- crypto/nrf_cc310_platform/include/nrf_cc310_platform_defines.h
- crypto/nrf_cc310_platform/include/nrf_cc310_platform_entropy.h
- crypto/nrf_cc310_platform/include/nrf_cc310_platform_mutex.h
- nfc/include/nfc_t4t_lib.h
* Doxygen 1.8.17 warns on duplicating return values; aggregate the duplicates in a single paragraph.
* Doxygen 1.8.17 warns on closing groups that were not previously opened, so get rid of those group closes. Should have no effect on 1.8.13.
> Fixes for Doxygen 1.8.17

- openthread/README.rst
This commit clarifies which OpenThread libraries have Thread Certification granted for each device and NCS release.
Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>
KRKNWK-8126
NCS PR: https://github.com/nrfconnect/sdk-nrf/pull/3396
> openthread: update certification documentation

- .checkpatch.conf
- .gitattributes
- CODEOWNERS
* sdk-nrfxlib was missing a configuration file for checkpatch; to avoid duplication just symlink it from sdk-nrf when running the compliance checks.
* Add git attribute to accept svg files as binary to avoid handling them as text files.
/cc @thst-nordic
> Fix checkpatch issues

- bsdlib/doc/gnss_extension.rst
- nrf_802154_sl/CHANGELOG.rst
- nrf_802154_sl/README.rst
- zboss/README.rst
All pages with sections should have a local ToC.
The heading for subpages should be "Subpages:", not "Contents:".
> doc: add local ToC and make ToC heading consistent

- nrf_modem/include/nrf_socket.h
> nrf_modem: fix doxygen warning in nrf_socket.h

- doc/links.txt
- nrf_modem/README.rst
- nrf_modem/doc/tls_dtls_configuration.rst
Add information of the supported cipher suites as a reference to the
modem documentation. Add simple example on how cipher suites used for
TLS session can be configured with socket options.
NCSDK-7725
> doc: nrf_modem: Add note regarding cipher suite support

- .checkpatch.conf
Exclude folder that cannot comply with the NCS coding standards due to
them including code that is developed by 3rd-party teams or companies.
> checkpatch: Exclude folders that contain 3rd-party code

- mpsl/CMakeLists.txt
This config may be selected when enabling clock calibration.
> mpsl: Allow TEMP_NRF5 with MPSL

- zboss/include/zb_osif.h
Prepare for ZBOSS update by adding a type and function declaration, required by future ZBOSS implementation.
Signed-off-by: Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>
> zboss: Add type definition for reset type

- zboss/include/zb_osif.h
The enum type has been changed to the series of defines.
Signed-off-by: Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>
> zboss: Align type definition for reset type

- .checkpatch.conf
For whatever reason checkpatch doesn't like a comma-separated list for
the set of excludes.
> checkpatch: Fix checkpatch.conf format

- crypto/Kconfig
- crypto/nrf_cc310_platform/include/nrf_cc3xx_platform_mutex.h
- crypto/nrf_cc310_platform/src/nrf_cc3xx_platform_mutex_zephyr.c
- crypto/nrf_cc312_platform/include/nrf_cc3xx_platform_mutex.h
- crypto/nrf_cc312_platform/src/nrf_cc3xx_platform_mutex_zephyr.c
- nrf_security/Kconfig
New lock variant fasten mutually exclusive access to CC3XX resources at the expense of a need to handle potential access failure
in the upper layer.
needed by: https://github.com/nrfconnect/sdk-nrf/pull/3339
> crypto: Add atomic variant for CC310 locking

- nrf_security/Kconfig
- nrf_security/cmake/kconfig_mbedtls_configure.cmake
- nrf_security/configs/nrf-config.h.template
Use zephyr's option to pass path to user config.
Jira:NCSDK-7689
Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>
> nrf_security: Make use of mbedtls user config

- softdevice_controller/CMakeLists.txt
- softdevice_controller/Kconfig
Using PERIPHERAL instead of PERIPH matches the library name and
the naming convention of the other configurations.
> softdevice_controller: Rename to SOFTDEVICE_CONTROLLER_PERIPHERAL

- crypto/Kconfig
- crypto/nrf_cc310_platform/src/nrf_cc3xx_platform_mutex_zephyr.c
- crypto/nrf_cc312_platform/include/nrf_cc3xx_platform_mutex.h
- crypto/nrf_cc312_platform/src/nrf_cc3xx_platform_mutex_zephyr.c
Make use of mutual exclusive peripheral on nRF53 Series devices for CC312 locking.
sdk-nrf linked PR: https://github.com/nrfconnect/sdk-nrf/pull/3736
> crypto: Add mutual exclusive peripheral lock variant for CC312

- crypto/nrf_cc310_platform/include/nrf_cc3xx_platform_mutex.h
It fixes building for nrf9160dk_nrf9160.
> crypto: Add missing define

- .github/workflows/compliance.yml
Using `compliancecheck` in sdk-nrf generates >500 undefined Kconfig
symbol references. Many of those are false warnings, but to allow time
for proper cleanup, then this commit resorts to only do KconfigBasic
check.
This means that undefined Kconfig symbols in the Kconfig tree are
reported but not outside the tree, such as source code, rst files, conf
files.
> compliancecheck: using KconfigBasic compliance check instead of Kconfig

- common.cmake
The `get_mbedtls_dir()` function was not handling user provided
ARM_MBEDTLS_PATH properly, as it was hiding the outer CMake variable
due to function argument of the same name.
This is now fixed by renaming the function argument from
ARM_MBEDTLS_PATH to ARM_MBEDTLS_PATH_ARG
-----
Manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/3810
> cmake: fixing user provided ARM_MBEDTLS_PATH

- crypto/doc/api.rst
- crypto/doc/nrf_cc310_mbedcrypto.rst
- crypto/nrf_cc310_mbedcrypto/include/mbedtls/cc3xx_kmu.h
- crypto/nrf_cc310_platform/include/nrf_cc3xx_platform_kmu.h
- Add reference to the API documentation in the cc3xx mbedcrypto library section
- Add the relevant category in the api.rst
- Add the correct group in the header file
Ref: NCSDK-7232
manifest pr: https://github.com/nrfconnect/sdk-nrf/pull/3435
> crypto: Add entry for KMU documentation for the cc3xx mbedcrypto

- crypto/CMakeLists.txt
- crypto/Kconfig
- nrf_security/Kconfig
-crypto: nrf_security Kconfig cleanup 
-crypto: Link platform and mbecrypto libs when nrf security is disabled
-crypto: Link mbedcrypto_cc3xx_imported when NRF_CC3XX_PLATFORM is set
Ref: NCSDK-8125
Relevant nrf PR: [sdk-nrf/pull/3793](https://github.com/nrfconnect/sdk-nrf/pull/3793)
> crypto: Link platform and mbecrypto libs when nrf security is disabled

- crypto/CMakeLists.txt
- crypto/Kconfig
- nrf_security/Kconfig
Reverting addition of CSPRNG for ENTROPY_CC3XX
Manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/3898
Manifest PR also include commit reverts
> Revert #397

- nrf_security/doc/backend_config.rst
Update the nrf_security RST file with tables listing the features
supported by different cryptographic algorithms.
This is the current output, some information is missing and needs to be provided, marked as TBD.
[Backend configurations and supported features — nrfxlib 1.4.99 documentation.pdf](https://github.com/nrfconnect/sdk-nrfxlib/files/5932417/Backend.configurations.and.supported.features.nrfxlib.1.4.99.documentation.pdf)
I'm still figuring out if line breaks are possible within a cell.
> doc: add tables with supported features to nrf_security

- nrf_security/Kconfig
- nrf_security/doc/backend_config.rst
-Removing Edwards25519 (alias for Curve25519) to prevent
assuming this configuration means Ed25519 is supported.
-Removing Edwards448 (alias for Curve448) to prevent
assuming this configuration means Ed448 is supported.
manifest pr: https://github.com/nrfconnect/sdk-nrf/pull/3968
> nrf_security: Removing alias Edwards25519 and Edwards448

- nrf_security/Kconfig
- nrf_security/cmake/kconfig_mbedtls_configure.cmake
- nrf_security/configs/nrf-config.h.template
- nrf_security/src/backend/entropy/entropy_poll.c
- nrf_security/src/mbedtls/CMakeLists.txt
Build the implementation of mbedtls_hardware_poll
that MbedTLS library can use to obtain entropy from cryptocell
even when call is done from non-secure domain.
Jira:NCSDK-8203
Signed-off-by: Pawel Dunaj <pawel.dunaj@nordicsemi.no>
> nrf_security: Expand hardware entropy wrapper to non-secure domain

- zboss/Kconfig
- zboss/development/CMakeLists.txt
- zboss/production/CMakeLists.txt
After adding a dependency on the nrfxlib module inside ZBOSS sources,
there is no need to define zboss-extensions CMake target.
Due to the Kconfig option override rules, the library type symbol has to
be dependent on the existance of ZBOSS sources in the west project.
After adding the dependency - the overriding Kconfig will be processed
after the one that intorduces option with defaults.
Signed-off-by: Tomasz Chyrowicz <tomasz.chyrowicz@nordicsemi.no>
> zboss: Simplify ZBOSS CMake targets

- nrf_security/src/mbedtls/CMakeLists.txt
-Implement the mbedtls_hardware_poll only when the cc3xx_backend is
disabled.
Ref: NCSDK-8488
> nrf_security: Hardware poll only when cc3cc_platform is disabled

- zboss/Kconfig
Make ZBOSS symbols dependent on ZIGBEE symbol.
> zboss: kconfig: add dependency on ZIGBEE symbol

- crypto/nrf_cc310_mbedcrypto/CHANGELOG.rst
- crypto/nrf_cc310_platform/CHANGELOG.rst
- mpsl/CHANGELOG.rst
- nrf_modem/doc/CHANGELOG.rst
- nrf_modem/doc/ug_nrf_modem_porting_os.rst
- softdevice_controller/CHANGELOG.rst
Updated terminology for "bug fix" and "timeout".
"Bugfix" and "time-out" are not allowed.
> doc: style: update terms for consistency

- nrf_modem/doc/CHANGELOG.rst
> nrf_modem: doc: fix errnous doc keyword

- softdevice_controller/Kconfig
This makes it possible to run applications using both advertising and
scanning.
> softdevice_controller: Use broadcaster/observer to select lib variant

- zboss/CHANGELOG.rst
Updated header to NCS 1.5.1 after release took place.
> doc: zboss: update changelog header

- CODEOWNERS
Replaces @hurricaneFromMoscow.
Signed-off-by: Thomas Stenersen <thomas.stenersen@nordicsemi.no>
> codeowners: Make @carlopaparo code owner for MPSL

- nrf_modem/Kconfig
Removes the imply FPU kconfig entry in NRF_MODEM.
Previously, this would fail linking when TFM was enabled, as that forces
FP_SOFTABI, which there is no binary for. The intent of the original
encourage FPU usage when available, but with TFM, this is no longer
valid.
Signed-off-by: Trond Einar Snekvik <Trond.Einar.Snekvik@nordicsemi.no>
> nrf_modem: Do not imply CONFIG_FPU

- doc/links.txt
- openthread/README.rst
Update the information about OpenThread prebuild libraries and
replace the list of certified libraries with links to the
compatibility matrices.
> doc: thread: update certification information

- nrf_security/Kconfig
When using 'select NORDIC_SECURITY_BACKEND' is modules, such as
OpenThread or Pelion, then config settings get stuck and user cannot
select another security configuration group.
The NORDIC_SECURITY_PROMPTLESS allows modules like Pelion or OpenThread
to disable the prompt when using pre-defined configuration groups.
> nrf_security: kconfig: support promptless configurations

- nrf_security/cmake/kconfig_mbedtls_configure.cmake
-This is a fix for the fix in the commit: 8aa0425
-The previous fix populated the cmake variable late and
it didn't make it available when the configuration file
for single oberon/vanilla was created.
sdk-nrf PR: [pull/4928](https://github.com/nrfconnect/sdk-nrf/pull/4928)
Ref: NCSDK-10057
> nrf_security: Configure the ECDSA_DETERMINISTIC early

- nrf_modem/doc/api.rst
This commit adds a note to the `nrf_select` documentation
description specifying that the functionality is currently
not supported.
Signed-off-by: Mirko Covizzi <mirko.covizzi@nordicsemi.no>
> nrf_modem: add note regarding `nrf_select` support

- doc/links.txt
Adds link to Bluetooth specification to doc/links.txt
Signed-off-by: Timothy Keys <timothy.keys@nordicsemi.no>
> doc: add Bluetooth specification link

- mpsl/CHANGELOG.rst
- nfc/CHANGELOG.rst
- nrf_802154/doc/CHANGELOG.rst
- zboss/CHANGELOG.rst
Changed master heading to 1.6.1 in nrfxlib changelogs.
> doc: update changelogs for 1.6.1

- nrf_security/Kconfig
-Adds a Kconfig variable for the
MBEDTLS_KEY_EXCHANGE_SOME_PSK_ENABLED configuration
-This is needed for the TLS on zephyr to work
-PSK is always enabled in our configuration so this
should not be configurable
sdk-nrf PR: [pull/5033](https://github.com/nrfconnect/sdk-nrf/pull/5033)
> nrf_security: Add SOME_PSK_ENABLED config

- .gitlint
- CODEOWNERS
Add a .gitlint config file to allow for the user defined commit rules in zephyr/scripts/gitlint to be used. 
Ref: NCSDK-3186
Signed-Off-By: William Hamshaw william.hamshaw@nordicsemi.no
> gitlint: Add gitlint config

- CODEOWNERS
Replaces @carlopaparo.
Signed-off-by: Thomas Stenersen <thomas.stenersen@nordicsemi.no>
> mpsl: Set @rugeGerritsen as code owner

- mpsl/doc/cx.rst
Fixes abbreviated mentions of nRF Connect SDK.
Also removes reference to a non-public document.
This was supposed to be part of PR #534 but was causing it to fail compliance for some reason.
Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>
> doc: style fix to radio coexistence documentation

- softdevice_controller/Kconfig
Run Bluetooth mesh in NCS with SoftDevice Controller by default.
Signed-off-by: Pavel Vasilyev <pavel.vasilyev@nordicsemi.no>
> Bluetooth: Mesh: Switch default BLE controller for mesh to SDC

- mpsl/doc/clock.rst
- mpsl/doc/fem.rst
- mpsl/doc/mpsl.rst
Applied several formatting and style edits.
Checked documentation before NCS 1.7.0 release.
NCSDK-11020.
-----
manifest PR: https://github.com/nrfconnect/sdk-nrf/pull/5497
> doc: nrfxlib doc check fixes

- crypto/CMakeLists.txt
-This fixes a build issue when CONFIG_FPU is enabled
with TF-M builds.
Ref: NCSDK-10877
> crypto: Fix oberon path when FPU is enabled

- nrf_security/cmake/extensions.cmake
- nrf_security/cmake/symbol_rename_archive_script.cmake
The symbol rename archive script used a generator expression to pass
all objects to the symbol_rename_archive_script.cmake among other
arguments.
When there are many objects in the library, then the command execution
string becomes very long.
On Windows, long execution commands are
wrapped inside a bat-file.
This might look like:
...\post-build.bat 7eb3ae9870a59d55
Resulting in SES-NE to try to execute the post-build.bat including the
following SHA as a single command, which fails.
This is fixed by generating a CMake file with required arguments to
symbol_rename_archive_script.cmake, and the pass this settings file as
argument to the script.
Fixes: NCSDK-10510
> nrf_security: symbol rename script now passes settings through script

- CODEOWNERS
Remove joerchan from codeowners.
> CODEOWNERS: Remove joerchan from codeowners entries

- crypto/nrf_cc310_mbedcrypto/CHANGELOG.rst
- mpsl/CHANGELOG.rst
- nfc/CHANGELOG.rst
- nrf_802154/doc/CHANGELOG.rst
- softdevice_controller/CHANGELOG.rst
- zboss/CHANGELOG.rst
Changed master branch heading to nRF Connect SDK 1.7.0.
NCSDK-11022
> doc: update changelogs for NCS 1.7.0

- nrf_security/cmake/extensions.cmake
The `set(symbol_rename_include ...)` was missing a space between
arguments resulting in the following warning:
> CMake Warning (dev) at
>             /.../ncs/nrfxlib/nrf_security/cmake/extensions.cmake:652:
>  Syntax Warning in cmake code at column 32
>
>  Argument not separated from preceding token by whitespace.
> Call Stack (most recent call first):
>  /.../ncs/nrfxlib/nrf_security/CMakeLists.txt:185 (include)
> This warning is for project developers.  Use -Wno-dev to suppress it.
This commit adds the missing whitespace.
> cmake: nrf_security: add missing space between arguments

- nrf_security/CMakeLists.txt
Update mcuboot mbedcrypto config file name. This was always the name,
but commit message that added it uses the other name, probably changed
during code-review in trusted-firmware-m.
Don't set the config unless BL2 is enabled. Otherwise this will produce
a cmake warning when the config is not used.
> nrf_security: Update mcuboot mbedcrypto config file

- gzll/README.rst
- gzll/doc/integration_notes.rst
- Add configuration details to integrate Gazell Link Layer library to a NCS application.
- Point to GZLL user guide for more information.
- Remove the duplicated introduction that is copied from GZLL user guide.
Beefing up the Gazell user guides for the NCS configuration details. Will submit another PR to the sdk-nrf repo.
> doc: gzll: Clarify library integration

- crypto/nrf_cc310_platform/include/nrf_cc3xx_platform_derived_key.h
- crypto/nrf_cc310_platform/include/nrf_cc3xx_platform_hmac_drbg.h
- crypto/nrf_cc310_platform/include/nrf_cc3xx_platform_kmu.h
- crypto/nrf_cc312_platform/include/nrf_cc3xx_platform_derived_key.h
- crypto/nrf_cc312_platform/include/nrf_cc3xx_platform_hmac_drbg.h
- crypto/nrf_cc312_platform/include/nrf_cc3xx_platform_kmu.h
- nrf_security/include/mbedcrypto_glue/backend_ccm.h
- nrf_security/include/mbedcrypto_glue/backend_cmac.h
- nrf_security/include/mbedcrypto_glue/backend_dhm.h
- nrf_security/include/mbedcrypto_glue/backend_ecdsa.h
- nrf_security/include/mbedcrypto_glue/backend_rsa.h
- nrf_security/include/mbedtls/platform.h
Fixing doxygen for:
- nrf_cc3xx_platform_derived_key APIs
- nrf_cc3xx_platform_hmac_drbg APIs
- nrf_cc3xx_platform_kmu APIs
- Glue layer: CCM, CMAC, DHM, ECDSA and RSA
- Removing section in platform.h
ref: NCSDK-11065
ref: NCSDK-12725
> crypto: Fixing miscellaneous doc warnings

- crypto/doc/nrf_cc310_mbedcrypto.rst
- nrf_security/README.rst
- nrf_security/doc/backend_config.rst
- nrf_security/doc/backends.rst
- nrf_security/doc/configuration.rst
- nrf_security/doc/glue_layer.rst
Miscellaneous doc improvements.
In some parts the language is superfluous, in a few cases it's
wrong/misleading, overall it is OK.
Signed-off-by: Sebastian Bøe <sebastian.boe@nordicsemi.no>
> doc: nrf_security: Misc. doc improvements

- nfc/CHANGELOG.rst
- nrf_802154/doc/multiprotocol_support.rst
- nrf_modem/doc/CHANGELOG.rst
- nrf_modem/doc/architecture.rst
- nrf_modem/doc/ug_nrf_modem_porting_os.rst
- nrf_rpc/README.rst
- nrf_rpc/doc/architecture.rst
- nrf_security/doc/mbed_tls_header.rst
NCSDK-12222
Remove Latin abbreviations from the
sdk-nrfxlib documents.
Signed-off-by: divya pillai <divya.pillai@nordicsemi.no>
> doc: Remove latin from sdk-nrfxlib docs

- openthread/include/openthread-config-generic.h
This commit fixes macros redefined warnings by reverting last changes.
> openthread: fix redefined macros

- nrf_security/doc/configuration.rst
- softdevice_controller/doc/bluetooth_coex_example_diagrams.rst
Added missing ToC to BT External Radio Coexistence
examples and NSM Configuration documents.
Ref: NCSDK-13404
Signed-off-by: Pekka Niskanen <pekka.niskanen@nordicsemi.no>
> doc: add missing ToCs

- nrf_security/src/psa_crypto_driver_wrappers.c
Fix crypto issues discovered by TF-M regression tests.
Disallow the SHA-1 algorithm when included by in the secure image.
TF-M expects these to not be usable.
TF-M regression tests:
```
'TFM_S_CRYPTO_TEST_1010'
Description: 'Secure Unsupported Hash (SHA-1) interface'
'TFM_S_CRYPTO_TEST_1019'
Description: 'Secure Unsupported HMAC (SHA-1) interface'
```
Add workaround for oberon_verify_message not supporting using
key attributes with key pair. Export a public-only key
before calling oberon_verify_message.
NCSDK-13486
> nrf_security: Fix crypto issues for TF-M

- openthread/cmake/extensions.cmake
The path for nrf_security headers has changed.
Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>
> openthread: fix building from libraries

- nrf_802154/sl/include/platform/nrf_802154_irq.h
- nrf_802154/sl/platform/irq/nrf_802154_irq_baremetal.c
Negative `prio` are intended to allow ZLIs in zephyr platform
implementation.
Signed-off-by: Andrzej Kuros <andrzej.kuros@nordicsemi.no>
> nrf_802154: nrf_802154_irq_init signed prio to allow Zephyr's ZLI

- nrf_802154/driver/src/nrf_802154_aes_ccm.c
- nrf_802154/driver/src/nrf_802154_swi.c
- nrf_802154/driver/src/nrf_802154_trx.c
- nrf_802154/sl/include/platform/nrf_802154_irq.h
- nrf_802154/sl/platform/lp_timer/nrf_802154_lp_timer.c
`NRF_802154_IRQ_PRIORITY_ALLOWED` became deprecated when the `prio`
parameter of `nrf_802154_irq_init` is platform-dependent.
Signed-off-by: Andrzej Kuros <andrzej.kuros@nordicsemi.no>
> nrf_802154: remove deprecated NRF_802154_IRQ_PRIORITY_ALLOWED

- nrf_modem/doc/CHANGELOG.rst
* Fixed a bug where `nrf_modem_trace_processed_callback`
could free a wrong memory address resulting in a crash.
Signed-off-by: Emanuele Di Santo <emdi@nordicsemi.no>
Signed-off-by: Andreas Moltumyr <andreas.moltumyr@nordicsemi.no>
Signed-off-by: Eivind Jølsgard <eivind.jolsgard@nordicsemi.no>
> nrf_modem: version 1.5.1

- gzll/CHANGELOG.rst
- gzll/README.rst
Add a changelog file for GZLL.
The PR to check the documentation build is nrfconnect/sdk-nrf#6800.
> gzll: Add a changelog

- crypto/doc/nrf_cc310_mbedcrypto.rst
- crypto/doc/nrf_oberon.rst
This adds a list of supported algorithms for the CC3XX and Oberon PSA drivers.
Ref: NCSDK-12557
Ref: NCSDK-12563
> crypto: Add missing PSA driver supported algorithms for Oberon and CC3XX.

- mpsl/CHANGELOG.rst
- nfc/CHANGELOG.rst
- nrf_dm/doc/CHANGELOG.rst
- softdevice_controller/CHANGELOG.rst
- zboss/CHANGELOG.rst
Changed main branch heading to nRF Connect SDK v1.9.0
NCSDK-13405
Signed-off-by: Mia Koen <mia.koen@nordicsemi.no>
> doc: Version update for NCS 1.9.0

- gzll/doc/integration_notes.rst
- nrf_802154/doc/CHANGELOG.rst
- nrf_security/doc/backend_config.rst
- nrf_security/doc/configuration.rst
- nrf_security/doc/driver_config.rst
- nrf_security/doc/drivers.rst
- nrf_security/tfm/CMakeLists.txt
- zboss/README.rst
- zboss/doc/zboss_configuration.rst
The new Kconfig extension requires usage of :kconfig:option: role, since
it uses a language domain.
> Upmerge 22-03-03

- .github/test-spec.yml
- CODEOWNERS
Signed-off-by: Sebastian Wezel <sebastian.wezel@nordicsemi.no>
This PR is meant to be a starting point to create the .github/test-spec.yml
Which will work similar to the [sdk-nrf/.github/test-spec.yml](https://github.com/nrfconnect/sdk-nrf/blob/main/.github/test-spec.yml)
You can add changes to the `test-spec` branch. I'll combine them to a single commit on Friday (18.03)
> adding .github/test-spec.yml

- softdevice_controller/CHANGELOG.rst
- softdevice_controller/README.rst
Clarifies that Periodic Advertising is supported as
an experimental feature for nRF53 Series.
Signed-off-by: Wille Backman <wille.backman@nordicsemi.no>
> doc: Clarify that Periodic Advertising is experimental in nRF53 series

- .github/test-spec.yml
At the moment we are executing more CI than necessary when only updating MPSL and SDC. See https://github.com/nrfconnect/sdk-nrf/pull/7194#issuecomment-1078970199
This PR is a rewrite from https://github.com/nrfconnect/sdk-nrfxlib/pull/694, fixing the syntax. 
It cherry-picks the changes from https://github.com/nrfconnect/sdk-nrfxlib/pull/698 and https://github.com/nrfconnect/sdk-nrfxlib/pull/697
> Exclude some ci when changing mpsl and sdc

- nrf_modem/doc/gnss_interface.rst
Added a note that GNSS needs to be enabled before it can be configured or started.
Clarified when GNSS priority mode is automatically disabled.
> doc: nrf_modem: improve GNSS documentation

- crypto/CMakeLists.txt
Add TF-M compile flags required when enabling FPU in TF-M.
TF-M documentation on FPU support:
"Secure and non-secure libraries are compiled with COMPILER_CP_FLAG and
linked with LINKER_CP_OPTION for different FP ABI types. All those
libraries shall be built with COMPLIER_CP_FLAG"
NCSDK-14513
Revert "crypto: Add workaround for liboberon PSA API prefix
The workaround is no longer needed since the Oberon library no
longer calls psa_generate_random.
The workaround had some cmake dependency issues and the command
was always run, causing dependent targets to be re-run.
This reverts commit https://github.com/joerchan/nrfxlib/commit/be4f031dcf7617e6b18a49a58a18fd37221e4671.
> nrf_security: Fix TF-M FPU flags and TF-M relink dependency

- nrf_rpc/doc/img/EDITING.TXT
The figures for nrf_rpc documentation were updated to follow
current diagrams guidelines in #670. The information
contained in EDITING.TXT is no longer valid.
Signed-off-by: Dominik Kilian <Dominik.Kilian@nordicsemi.no>
> doc: Remove EDITING.TXT from nrf_rpc figures

- nrf_security/cmake/config_to_tf-m.cmake
Remove crypto partition heap size set based on the mbedtls heap size
configuration.
> nrf_security: Remove setting of crypto partition heap to mbedtls config

- crypto/CMakeLists.txt
This fixes linking crypto library by linking
the C library after crypto libraries.
> crypto: Fix linking crypto library

- nrf_rpc/Kconfig
- nrf_rpc/include/nrf_rpc_cbor.h
- nrf_rpc/nrf_rpc_cbor.c
TinyCBOR got deprecated and is being substituted by zcbor.
Signed-off-by: Dominik Ermel <dominik.ermel@nordicsemi.no>
> nrf_rpc: Move from TinyCBOR to zcbor

- mpsl/license.txt
- nfc/license.txt
- nrf_dm/license.txt
- softdevice_controller/license.txt
- zboss/license.txt
A new tool for a license report generation will be introduced in
the new NCS. It will recognize licenses from the source code,
but it needs additional information for binary files. This commit
adds special tag to license files allowing clear binary files
license recognition.
Manifest update PR: https://github.com/nrfconnect/sdk-nrf/pull/7701
The tool is in the PR:
https://github.com/nrfconnect/sdk-nrf/pull/7209
You can see sample generated report from all `.a` file in nrfxlib repository:
https://doki-nordic.github.io/test-demo-docs/temp/nrfxlib-binary.html
> license: Add tag for detecting license of binary files

- nrf_modem/doc/CHANGELOG.rst
* Minor improvements to 'nrf_modem_shutdown'.
* Fixed a bug where 'nrf_modem_build_version' did not give the correct
version number.
> nrf_modem: v2.0.1

- mpsl/doc/bluetooth_coex.rst
- softdevice_controller/CHANGELOG.rst
- softdevice_controller/README.rst
Remove "experimental support for AoA" in README
and CHANGELOG
Signed-off-by: Yuxuan Cai <yuxuan.cai@nordicsemi.no>
> softdevice_controller: production support for CTE AoA TX

- nrf_security/src/zephyr/CMakeLists.txt
- nrf_security/src/zephyr/mbedtls_partition.c
... to make it possible to build with `CONFIG_USERSPACE` enabled
(there is such definition in userspace.c in Zephyr but it is compiled
only when `CONFIG_MBEDTLS` is enabled, what is not the case here).
Ref.: NCSDK-15305
> nrf_security: Add definition of appmem partition for mbedtls library

- softdevice_controller/README.rst
Mark Periodic Advertising as not experimental on nRF53.
Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>
> softdevice_controller: Production support for Periodic Adv on nRF53

- nrf_dm/Kconfig
If the nrf_dm_high_precision_calc() function is being used, there is a
dependency to cmsis_dsp_matrix that was missing.
Verification in https://github.com/nrfconnect/sdk-nrf/pull/7879
Signed-off-by: Jan Müller <jan.mueller@nordicsemi.no>
> nrf_dm: Add missing cmsis dependency

- nrf_security/src/CMakeLists.txt
Add TF-M compile flags required when enabling FPU in TF-M.
TF-M documentation on FPU support:
"Secure and non-secure libraries are compiled with COMPILER_CP_FLAG and
linked with LINKER_CP_OPTION for different FP ABI types. All those
libraries shall be built with COMPLIER_CP_FLAG"
NCSDK-14513
> nrf_security: Add compile flags when built in TF-M with FPU enabled

- nrf_rpc/include/nrf_rpc.h
- nrf_rpc/nrf_rpc.c
This PR introduces protocol versioning for the nRF RPC library.
The protocol version range is exchanged  and checked between remote processor during the group initialization process.
> nRF RPC: Protocol versioning

- Jenkinsfile
This branch should use v1.9-branch branch of CI_LIB.
Signed-off-by: Jan Gałda <jan.galda@nordicsemi.no>
> ci: Fix CI_LIB's version

- mpsl/CHANGELOG.rst
- mpsl/doc/bluetooth_coex.rst
Update the changelog to state that we have production support for 1-wire
coex and remove experimental note from the coex documentation.
Related PR in sdk-nrf to update the kconfig: https://github.com/nrfconnect/sdk-nrf/pull/8280
Signed-off-by: Thoresen, Olav <olav.thoresen@nordicsemi.no>
> doc: mpsl: Update docs to mark 1-wire coex as supported for production

- openthread/cmake/extensions.cmake
When building OpenThread libraries, add information about the
GCC version that was used to the configuration text file.
Signed-off-by: Eduardo Montoya <eduardo.montoya@nordicsemi.no>
KRKNWK-14765
> openthread: add information about GCC version

- openthread/Kconfig
The anonymous choice that is used for selecting Nordic library configuration doesn't allow to override a default value in any other place of Kconfig structure and forces to that in the .conf file. It is not possible to set this symbol value in some Kconfig.xxx file that could be used for defining a subset of configuration for some specific purpose.
Added OPENTHREAD_NORDIC_LIBRARY_CONFIGURATION name to anonymous choice to allow overriding its default value in the other places of Kconfig structure.
Signed-off-by: Kamil Kasperczyk <kamil.kasperczyk@nordicsemi.no>
> openthread: Added a name to anonymous NORDIC_LIBRARY choice

- nrf_security/Kconfig.tls
- nrf_security/cmake/legacy_crypto_config.cmake
- nrf_security/cmake/psa_crypto_config.cmake
Make it possible to see internal Mbed TLS logs.
Also enable extended master secret DTLS option.
> Add mbedtls debug output

- nrf_security/src/psa_crypto_driver_wrappers.c
-This makes sure that the cipher_update for cc3xx
always returns success when the input length is
0. This commit should be dropped when a new
version of the runtime library is released.
Ref: NCSDK-16036
> nrf_security: Fix for cipher_update with 0 input

- .github/test-spec.yml
Narrow the pattern that triggers Gazelle, NFC and Find My tests.
At least NFC and Find My tests were triggered by manifest updates
to sdk-nrf that only updated the Modem library, to which
they are completely unrelated.
> test: update test-spec.yml

- softdevice_controller/README.rst
doc fix.
Added a link to the Propreitary features table to link
from the [Bluetooth LLPM sample doc.](https://developer.nordicsemi.com/nRF_Connect_SDK/doc/latest/nrf/samples/bluetooth/llpm/README.html#requirements)
> doc: Doc fix

- lc3/README.rst
- mpsl/CHANGELOG.rst
- nfc/CHANGELOG.rst
- nrf_802154/README.rst
- nrf_802154/doc/CHANGELOG.rst
- nrf_802154/doc/rd_limitations.rst
- softdevice_controller/CHANGELOG.rst
Updated changelogs in nrfxlib with 2.1.0 sections.
> doc: update changelogs for 2.1.0 release

- .github/workflows/compliance.yml
The script requires version > 2.0.
Aligns with the version used in sdk-nrf.
Signed-off-by: Maciej Perkowski <Maciej.Perkowski@nordicsemi.no>
> workflow: compliance: bump junitparser version

- nrf_rpc/Kconfig
- nrf_rpc/include/nrf_rpc_cbor.h
We need to have multiple states to be able to decode nested lists or
maps.
Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>
> nrf_rpc: Make number of states configurable

- crypto/nrf_cc310_platform/src/nrf_cc3xx_platform_mutex_zephyr.c
- crypto/nrf_cc310_platform/src/nrf_cc3xx_platform_no_mutex_zephyr.c
- crypto/nrf_cc312_platform/src/nrf_cc3xx_platform_mutex_zephyr.c
- crypto/nrf_cc312_platform/src/nrf_cc3xx_platform_no_mutex_zephyr.c
- lc3/src/sw_codec_lc3.c
- nrf_rpc/nrf_rpc.c
- nrf_security/src/legacy/entropy_poll.c
- nrf_security/src/psa/psa_eits_zephyr_settings.c
Updates needed for NCS upmerge 2022.09.27.
*treewide: Update Zephyr include paths*
- Add `zephyr/` prefix where needed
- Replace deprecated `<zephyr/zephyr.h>` with `<zephyr/kernel.h>`
*nrf_rpc: Fix array out-of-bounds warnings*
The newest zephyr-sdk contains GCC version that started
to complain about array out-of-bounds. This is false positive
because the actual content of the array is added by the linker.
> Upmerge 2022.09.27

- crypto/doc/nrf_cc310_mbedcrypto.rst
- nfc/doc/integration_notes.rst
- nrf_modem/doc/ug_nrf_modem_porting_os.rst
Replaced "domains" with SPE and NSPE.
NCSDK-17646.
> doc: update secure and non-secure terminology

- softdevice_controller/CHANGELOG.rst
Added section about v2.1.2, and note about Errata 158 on nrf53
Signed-off-by: Martin Tverdal <martin.tverdal@nordicsemi.no>
> doc: Update SoftDevice Controller release notes

- nrf_rpc/CHANGELOG.rst
- nrf_rpc/include/nrf_rpc.h
- nrf_rpc/include/nrf_rpc_cbor.h
- nrf_rpc/nrf_rpc.c
- nrf_rpc/nrf_rpc_cbor.c
This adds support to initialize transports independently. 
If one transport fails to bond, the others are attempted to initialize.
> nrf_rpc: Initialize transports independently of each other

- zboss/development/include/zcl/zb_zcl_ota_upgrade.h
- zboss/production/include/zcl/zb_zcl_ota_upgrade.h
[KRKNWK-15657]
Add ota upgrade sub header structure due to warnings about array-bounds.
Associated with:
https://github.com/nrfconnect/sdk-nrf/pull/9290
Signed-off-by: Mariusz Poslinski <mariusz.poslinski@nordicsemi.no>
> zboss: add ota upgrade sub header structure

- README.rst
Removing a redundant colon from the nrfxlib ToC.
Signed-off-by: Anna Kielar <anna.kielar@nordicsemi.no>
> doc: a redundant character removal

- nrf_security/Kconfig
- nrf_security/src/zephyr/CMakeLists.txt
This fixes two issues that we found while trying to build some zephyr samples.
1) When CONFIG_MBEDTLS and CONFIG_USERSPACE are enabled the mbedtls_partition is defined
by zephyr so nrf_security should not define it. Redefinition of the partition is not allowed and is causing 
a build failure.
2) The CONFIG_MBEDTLS_MAC_MD5_ENABLED was not defined in nrf_security before. This was
originally defined in: zephyr/modules/mbedtls/Kconfig.tls-generic. But we have a patch on this file which 
does not allow this Kconfig to be enabled when CONFIG_NRF_SECURITY is not enabled. 
The addition here allows the Kconfig to be enabled since
it is used by some network protocols and it is supported by nrf_security. 
Ref: NCSDK-17995
> nrf_security: Fix mbedlts Kconfig issues for MD5 and MbedTLS

- nrf_security/src/psa_crypto_driver_wrappers.c
This fixes an issue with the import key function of the psa_crypto_driver_wrappers.c
in which we returned PSA_ERROR_INVALID_ARGUMENT when only one driver
was enabled (CC3XX/Oberon) and it returned PSA_ERROR_NOT_SUPPORTED.
We now return the error code of the driver which matches what the PSA
tests are expecting.
There are also some minor cleanups for the file which doesn't affect functionality
at all.
Ref: NCSDK-17707
> nrf_security:  Return code  fixes + minor cleanups for PSA driver wrapper

- nrf_security/src/psa_crypto_driver_wrappers.c
This removes the workaround described in NCSDK-16036. The issue was the the cc3xx_cipher_update didn't set the output length to 0 when the input had length 0. Now the cc3xx_cipher_udpate sets the output_length correctly so the workaround is not needed.
> nrf_security: Remove workaround in cipher_update

- common.cmake
- nrf_security/CMakeLists.txt
- openthread/cmake/extensions.cmake
Zephyr's fork of mbed TLS has been updated to match a version required by nRF Security.
This means that the nRF Connect SDK manifest file points to the Zephyr fork and no longer points at arm mbed TLS github repository.
Therefore mbed TLS is now available as a Zephyr module and nRF Security can therefor use `ZEPHYR_MBEDTLS_MODULE_DIR` directly and thus remove the need for a custom `get_mbedtls_dir()` function.
> cmake: remove get_mbedtls_dir() and use ZEPHYR_MBEDTLS_MODULE_DIR

- nrf_modem/doc/gnss_interface.rst
Added formula for calculating the current UTC time at the time of an 1PPS pulse.
> doc: nrf_modem: document how to calculate 1PPS pulse time

- nrf_security/Kconfig.legacy
This removes NRF_SECURITY_RNG since we now
fully support the Zephyr RNG model for TF-M and
secure only targets. It also selects the PSA RNG
driver from Zephyr for TF-M targets.
Ref: NCSDK-14509
> nrf_security: Remove NRF_SECURITY_RNG

- .github/test-spec.yml
Added an entry for CI-cloud-test that will run the downstream job of test-fw-nrfconnect-nrf-iot_cloud when any of the listed modules change.
See IRIS-5423
Signed-off-by: Tony Le <tony.le@nordicsemi.no>
> ci: Updated test-spec.yml for Cloud CI testing

- nrf_802154/sl/include/platform/nrf_802154_platform_sl_lptimer.h
The platform interface has been extended with functions that prepare, update
and clear (D)PPI bindings for triggering hardware task.
Signed-off-by: Adam Zelik <adam.zelik@nordicsemi.no>
> nrf_802154: sl_lptimer platform extension for SL timer HW task

- common.cmake
- mpsl/Kconfig
Allows the build system to find and build with an MPSL library compiled for the babblesim target.
Only intended for internal use for now.
Signed-off-by: Jonathan Rico <jonathan.rico@nordicsemi.no>
> MPSL: Allow linking with MPSL compiled for babblesim

- CMakeLists.txt
Moving mpsl under softdevice controller,
without this we get linker errors when linking with un-obfuscated softdevice-controller and mpsl libraries.
linker errors like:
"undefined reference to `mpsl_cx_granted_ops_get`
Signed-off-by: Martin Tverdal <martin.tverdal@nordicsemi.no>
Manifest PR https://github.com/nrfconnect/sdk-nrf/pull/10345
> softdevice_controller: mpsl: Making debugversion compile work

- nrf_security/cmake/extensions.cmake
nrf_security_add_zephyr_options() now adds a dependency to zephyr_interface for libraries which requires include paths defined by zephyr_interface.
This ensures that all header files generated through zephyr_interface sub-dependencies will be available upon compilation of the library passed to nrf_security_add_zephyr_options().
Examples of headers that could otherwise be missing:
- syscall_list.h
- kobj-types-enum.h
> cmake: nrf_security_add_zephyr_options() adds dependency to z_interface

- nrf_modem/doc/gnss_interface.rst
Added a note that 1PPS accuracy is not guaranteed when LTE is active at the same time.
> doc: nrf_modem: add note for 1PPS usage with LTE

- nrf_security/src/psa_crypto_driver_wrappers.c
This makes sure that we always call the function
psa_import_key_into_slot when no crypto accelerator import_key functionality is available. This is needed because our Oberon library does not support import_key for symmetric keys but it supports doing operations with symmetric keys. The psa_import_key_into_slot function always includes the logic for symmetric keys, which has minor effects in increasing the code size. The support for asymmetric keys on the other hand is configurable which is a good for us since Oberon does support
import_key with asymmetric keys.
> nrf_security: Use default import_key from PSA core

- nrf_security/configs/nrf-config.h
- nrf_security/src/CMakeLists.txt
- nrf_security/src/debug_init.c
Adds support for CONFIG_MBEDTLS_DEBUG, so that debug log callbacks and log level is set up for MBEDTLS.
> nrf_security: Enable support for MBEDTLS debug logs

- nrf_security/cmake/legacy_crypto_config.cmake
- nrf_security/include/mbedtls/platform.h
- nrf_security/tfm/CMakeLists.txt
Remove usage of HEAP in platform.c.
The functions free and calloc pulls in heap from the C standard library.
We always call mbedtls_platform_set_calloc_free to set alternative
heap management functions so this is unneccesary.
NCSDK-19561
TF-M uses the mbedtls_platform_set_printf to set 'printf' as the
mbedtls logging function. This is unneccary as we already have set
'printf' as the default function in platform.h, but we don't want to
modify the TF-M source code unless we have to.The functions free and calloc pulls in heap from the C standard library.
We always call mbedtls_platform_set_calloc_free to set alternative
heap management functions so this is unneccesary.
> TF-M: Remove usage of HEAP

- .github/test-spec.yml
Wi-Fi crypto has dependencies on MbedTLS, so, add an entry to the test-spec to catch any breaking changes.
> ci: Add Wi-Fi crypto dependency to test-spec

- crypto/CMakeLists.txt
- crypto/Kconfig
Delete the Kconfig option HW_CC3XX_INTERRUPT as it is not supported.
> crypto: Delete Kconfig HW_CC3XX_INTERRUPT

- nrf_security/configs/psa_crypto_config.h.template
TF-M's build system passes -DMBEDTLS_PSA_CRYPTO_DRIVERS which will define the variable to 1.
> nrf_security: Fix redefinition warning

- .github/test-spec.yml
Update file patterns in test-spec.yml in order to optimize integration plan triggers
> test-spec: update file patterns for thread, homekit and matter

- nrf_security/doc/driver_config.rst
-Bugfixes for PSA crypto config documentation and addition of Oberon PSA driver support
ref: NCSDK-19412
ref: NCSDK-21654
> Crypto doc fixes

- softdevice_controller/CHANGELOG.rst
- softdevice_controller/README.rst
For the periodic advertising with responses advertiser and scanner, the support is production ready.
> doc: Update Periodic Advertising with Responses supporting

- softdevice_controller/CMakeLists.txt
If softdevice controller is build from sources as a submodule it should not use header files exported to nrfxlib. These header files may be not changed in SDC used to build. That could end with strange runtime errors that are hard to track.
Signed-off-by: Piotr Pryga <piotr.pryga@nordicsemi.no>
> softdevice_controller: Do not use header files when SDC build from src

- nrf_rpc/CHANGELOG.rst
- nrf_rpc/nrf_rpc.c
This commit enables the initialization of nRF RPC more than once. 
Subsequent initialization of an already properly initialized nRF RPC will succeed.
Manifest update: https://github.com/nrfconnect/sdk-nrf/pull/10775
> nrf_rpc: Allow multiple initialization of nRF RPC

- .github/test-spec.yml
Update test-specification after nrf_security move. The nrf_security subsystem was moved to the sdk-nrf repository, so it needs to be removed from the test-specification of this repository.
> test-spec.yml: Update test-specification after nrf_security move

- mpsl/CMakeLists.txt
- mpsl/fem/CMakeLists.txt
This PR adds the possibility to include FEM libraries if they are built separately from MPSL and placed in the mpsl/fem directory. The contents of the `mpsl/fem` directory will be filled when updating MPSL and SDC revisions.
> mpsl: allow for fem as separate libs

- openthread/CMakeLists.txt
Fix for changed path of mbedtls config.
> cmake: openthread: Fix library copy target for openthread.

- openthread/cmake/extensions.cmake
When building from libraries openthread took CONFIG_MBEDTLS_CFG_FILE form incorrect location. This commit fixes that.
> cmake: openthread: Fix mbed tls config file location.

- nrf_rpc/CHANGELOG.rst
- nrf_rpc/nrf_rpc_cbor.c
Fixed an issue where the nrf_rpc_cbor_cmd_rsp
function decodes only the first response element.
> nrf_rpc: Fix command response decoding

- crypto/doc/CHANGELOG_cc310_bl.rst
- crypto/doc/CHANGELOG_cc3xx_mbedcrypto.rst
- crypto/doc/CHANGELOG_cc3xx_platform.rst
- crypto/doc/CHANGELOG_oberon.rst
- crypto/doc/nrf_cc310_bl.rst
- crypto/doc/nrf_cc3xx_mbedcrypto.rst
- crypto/doc/nrf_cc3xx_platform.rst
Update crypto docs to refer to nrf91 instead of nrf9160 for
portability.
Also, update one place where nrf53 was omitted.
Only the most recent changelog is updated as changelogs do not really
need to be updated. We only update the changelogs to make it easier to
copy-paste the changelog on the next release.
> doc: crypto: Refer to nrf91 instead of nrf9160 

- zboss/production/src/zcl/zcl_color_control_commands.c
This commit initializes structures that may be used uninitialized as reported by compiler in warning.
> zboss: Fix maybe-uninitialized warning in ZCL layer

- doc/links.txt
- nrf_modem/doc/modem_trace.rst
- nrf_modem/doc/sockets.rst
The Cellular Monitor tool replaces the trace collector(s) and the LTE Link monitor.
Documents are updated with these details
> doc: Cellular Monitor tool replaces Trace Collector and LTE Link monitor

- doc/links.txt
- nrf_modem/doc/gnss_interface.rst
Updated documentation to use the term "A-GNSS" instead of "A-GPS".
Removed notes related to legacy MFWs.
Improved dynamics mode description.
> nrf_modem: doc: gnss_interface: Update conceptual documentation

- doc/links.txt
- nrf_modem/doc/at_interface.rst
Rename "nRF91 AT Commands Reference Guide" to
"nRF9160 AT Commands"
> doc: Rename the nRF91 AT Commands Reference Guide

- nrf_modem/doc/api.rst
Fixed incorrect group links in GNSS API documentation.
> nrf_modem: doc: Fix GNSS API enums

- nrf_modem/doc/gnss_interface.rst
Updated GNSS documentation because 1PPS feature is not supported when LTE is enabled.
> nrf_modem: doc: Update GNSS 1PPS documentation

- lc3/README.rst
Moved QDID information for LC3 to a section that can be included in sdk-nrf. OCT-2692.
> doc improvement: lc3: format qdid info for reuse

- .github/test-spec.yml
HomeKit Accessory Development Kit has been deprecated and removed from NCS.
> testspec: remove HomeKIt

- crypto/Kconfig
Remove the configurations for cryptocell usable and use the standard HAS_HW configurations instead.
> crypto: Remove cryptocell usable configs and use HAS_HW instead

- .github/test-spec.yml
We have sufficient coverage by building and running other tests.
> CI: Don't run sdk-sidewalk tests on SDC updates

- .github/test-spec.yml
These were missed when the driver is restructured and moved to nrfxlib.
> ci: Fix missing Wi-Fi tests

- nrf_wifi/README.rst
In the ToC a prefix helps disambiguate.
> nrf_wifi: doc: Add a prefix

- .github/labeler.yml
This should be automatically added for nrf Wi-Fi related changes. This is used to enforce a mandatory QA upvote even though it is ready to be merged.
> ci: Add a new Wi-Fi QA required label

- nrf_modem/Kconfig
Introduce a Kconfig choice for the binary version.
> nrf_modem: update build system files

- nrf_wifi/bus_if/bal/src/bal.c
- nrf_wifi/bus_if/bus/qspi/src/qspi.c
- nrf_wifi/bus_if/bus/spi/src/spi.c
- nrf_wifi/fw_if/umac_if/src/cmd.c
- nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
- nrf_wifi/fw_if/umac_if/src/event.c
- nrf_wifi/fw_if/umac_if/src/fmac_ap.c
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- nrf_wifi/fw_if/umac_if/src/fmac_vif.c
- nrf_wifi/fw_if/umac_if/src/radio_test/fmac_api.c
- nrf_wifi/fw_if/umac_if/src/rx.c
- nrf_wifi/fw_if/umac_if/src/tx.c
- nrf_wifi/hw_if/hal/src/hal_api.c
- nrf_wifi/hw_if/hal/src/hal_fw_patch_loader.c
- nrf_wifi/hw_if/hal/src/hal_interrupt.c
- nrf_wifi/hw_if/hal/src/hal_mem.c
- nrf_wifi/hw_if/hal/src/hal_reg.c
- nrf_wifi/hw_if/hal/src/hpqm.c
- nrf_wifi/hw_if/hal/src/pal.c
- nrf_wifi/utils/src/list.c
- nrf_wifi/utils/src/util.c
The functions nrf_wifi_osal_log_err, nrf_wifi_osal_log_info and nrf_wifi_osal_log_dbg use log macros, which already adds newline. No need to add "\n" in end of these function calls. Remove "\n" from these function calls.
> nrf_wifi: Remove extra logline from log

- nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
The maximum buffer size should include MTU and headroom, fix the check.
> nrf_wifi: Fix maximum transmit buffer size check

- CODEOWNERS
This makes it easier to add and remove code owners for these areas. These folders are well known by the entire team.
> CODEOWNERS: Use @ncs-dragoon as code owners for MPSL and SDC

- nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
MTU doesn't include any L2 overhead, so, we need to add Ethernet header len for maximum frame size that we can received from the networking stack.
Fixes SHEL-2214.
> nrf_wifi: Fix missing L2 header in max MSDU calculation

- .github/labeler.yml
This reverts commit 1d318c52025ae9fb61c720d6f6823670ac58e8a7.
The process on how to use the label is not streamlined yet, so, for now reverting this till it's sorted.
> Revert "ci: Add a new Wi-Fi QA required label"

- nrf_wifi/fw_if/umac_if/src/tx.c
The code commit provides a fix for a NULL point de-reference in the tx path for RAW TX. Since, the error check is for an abnormal condition, it is not hit usually. This fix prevents a null dereference when this abnormal condition is hit.
> nrf_wifi: Fix null point dereference in driver raw tx path

- mpsl/doc/mpsl.rst
The new KConfig option for MPSL allows to change the default assigned interrupt for low-priority processing. This allows for better interoperability with other SW modules such as ESB.
> doc: Add documentation for new KConfig option

- crypto/Kconfig
- Ensure that nrf_cc310_bl is only enabled in NSIB and MCUboot
- Disable nrf_cc3xx_platform for NSIB
ref: NCSDK-25144
> crypto: Ensure correct CryptoCell libs for bootloaders

- CODEOWNERS
Replaced tomchy with milewr as Zigbee code owner.
> CODEOWNERS: Assign all Zigbee parts to milewr

- doc/links.txt
Add a link to the bluetooth specification and documents page. This will later be used in the isochronous channels documentation.
> doc: add link to Bluetooth specification page

- nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
- nrf_wifi/fw_if/umac_if/src/cmd.c
[SHEL-1780] By default UMAC can scan all channles including DFS channels. Disable DFS channels in scan operation only if requested by user.
[SHEL-1780]: https://nordicsemi.atlassian.net/browse/SHEL-1780?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> nrf_wifi: Disbale DFS channels in scan

- nrf_wifi/fw_if/umac_if/src/rx.c
- nrf_wifi/fw_if/umac_if/src/tx.c
- nrf_wifi/hw_if/hal/inc/hal_api.h
- nrf_wifi/hw_if/hal/inc/hal_structs.h
- nrf_wifi/hw_if/hal/src/hal_api.c
During interface down we de-initialize the FMAC FW (different from FMAC de-init, which is never called in Zephyr), we have a lock to synchronize the states with interrupt (RX or TX_DONE), but this doesn't avoid the interrupt handlers to be executed later causing crashes as the code doesn't have proper NULL checks.
Add a HAL status that can be used to silently ignore the interrupts if the HAL is disabled to fix crashes. This status is also protected by the same lock used to synchronize these two events.
Fixes SHEL-2359.
> nrf_wifi: Fix synchronization b/w down vs. RX

- nrf_wifi/fw_if/umac_if/src/tx.c
Remove a debug log message which has come into checked in code unintentionally
> nrf_wifi: Remove unwanted debug message in checkin

- nrf_wifi/bus_if/bal/inc/bal_ops.h
- nrf_wifi/fw_if/umac_if/inc/default/fmac_api.h
- nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h
- nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
- nrf_wifi/fw_if/umac_if/inc/fmac_structs_common.h
- nrf_wifi/fw_if/umac_if/inc/fmac_util.h
- nrf_wifi/fw_if/umac_if/inc/radio_test/fmac_api.h
- nrf_wifi/fw_if/umac_if/inc/radio_test/fmac_structs.h
- nrf_wifi/hw_if/hal/inc/hal_api.h
- nrf_wifi/hw_if/hal/inc/hal_structs.h
- nrf_wifi/os_if/inc/osal_api.h
- nrf_wifi/os_if/inc/osal_ops.h
- nrf_wifi/os_if/inc/osal_structs.h
- nrf_wifi/utils/inc/list.h
- nrf_wifi/utils/inc/queue.h
- nrf_wifi/utils/inc/util.h
[CAL-3923] Make OS agnostic self-contained way
(i.e., without relying on C headers)
Purpose to fully use the Zephyr/Linux internal headers to take advantage off architecture specific
accelerators (esp. Linux).
[CAL-3923]: https://nordicsemi.atlassian.net/browse/CAL-3923?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> nrf_wifi: Osal hdr clean up

- nrf_wifi/fw_if/umac_if/inc/fmac_structs_common.h
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
Regulatory channel attributes to be provided along with regulatory country code.
> nrf_wifi: Add regulatory channel attributes

- nrf_wifi/fw_if/umac_if/inc/default/fmac_api.h
- nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
- nrf_wifi/fw_if/umac_if/inc/fmac_cmd.h
- nrf_wifi/fw_if/umac_if/src/cmd.c
- nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- nrf_wifi/hw_if/hal/inc/fw/phy_rf_params.h
- nrf_wifi/utils/src/util.c
[SHEL-1493]: Replace the string with a structure definition for better readability.
[SHEL-1493]: https://nordicsemi.atlassian.net/browse/SHEL-1493?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> nrf_wifi: Replace RF parameter string with a structure definition.

- nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- nrf_wifi/hw_if/hal/inc/hal_api.h
- nrf_wifi/hw_if/hal/src/hal_api.c
[SHEL-2310]: Modify host driver to read package type from OTP. Use this package type information to pick RF parameters.
[SHEL-2310]: https://nordicsemi.atlassian.net/browse/SHEL-2310?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> nrf_wifi: Support for CSP package in Host driver

- nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h
- nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
- nrf_wifi/fw_if/umac_if/src/event.c
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- nrf_wifi/fw_if/umac_if/src/fmac_util.c
- nrf_wifi/fw_if/umac_if/src/rx.c
This set of changes brings in Monitor mode driver changes, filter setting changes in driver for sniffer and TX injection changes for driver to handle TX injection as an NET_REQUEST_ETHERNET command
> Txinjection monitor changes

- .github/test-spec.yml
Few CIs are removed from mpsl&sdc test scope, due to the fact that many ble scenarios are already covered in ble CI
> test-spec: remove some CI labels from mpsl&sdc change

- nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
- nrf_wifi/fw_if/umac_if/inc/fmac_cmd.h
- nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
- nrf_wifi/fw_if/umac_if/src/cmd.c
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- nrf_wifi/hw_if/hal/inc/fw/rpu_if.h
SHEL-2395: Rename all occurrences of ble*/BLE*/bt*/BT* to sr*/SR* to have generic names in common code, to support coexistence with Short Range radios.
> nrf_wifi: Rename occurrences of bt*/ble* to sr*/SR*

- nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h
- nrf_wifi/fw_if/umac_if/inc/fmac_cmd.h
- nrf_wifi/fw_if/umac_if/inc/fmac_structs_common.h
- nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_umac_if.h
- nrf_wifi/fw_if/umac_if/src/event.c
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
When setting the regulatory wait for the change to take affect and check the status before returning to the caller.
Fixes SHEL-2458.
> nrf_wifi: Wait for regulatory change

- nrf_rpc/nrf_rpc_cbor.c
More arguments to zcbor_new_decode_state().
> nrf_rpc: Adapt to API changes in zcbor 0.8.0

- nrf_wifi/fw_if/umac_if/src/tx.c
Fix the NULL checks causing crash during de-init.
Fixes SHEL-2463.
> nrf_wifi: Fix the NULL checks

- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- nrf_wifi/hw_if/hal/inc/fw/phy_rf_params.h
Update to voltage and temperature based power backoff for CSP.
> nrf_wifi: Incorporate CSP related parameters in firmware

- nrf_wifi/fw_if/umac_if/src/fmac_util.c
This change adds the CONFIG_NRF700X_RAW_DATA_RX check for monitor mode to prevent monitor mode from being configured when driver is not compiled for the same.
It addresses SHEL-2461
> nrf_wifi: Add CONFIG_NRF700X_RAW_DATA_RX check in validity check API

- nrf_wifi/fw_if/umac_if/src/tx.c
This change updates raw tx failure update count when the firmware indicates a failure to send raw tx packet
> nrf_wifi: Update raw tx failure count when tx done indicates failure

- nrf_wifi/fw_if/umac_if/inc/default/fmac_structs.h
- nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- nrf_wifi/fw_if/umac_if/src/rx.c
filter settings have to be enabled for PROMISCUOUS mode. This change adds the config settings for filter and also corrects certain build issues for promiscuous mode
> nrf_wifi: Add promiscuous mode CONFIG for setting filter

- crypto/doc/api.rst
Several API docs were missing for the ocrypto library added them
Ref: NCSDK-21222
> doc: crypto: Add missing ocrypto APIs to doxygen

- .github/test-spec.yml
Removing these triggers has not been approved by Thread team.
> test-spec: restore `mpsl` triggers for `CI-thread-test` label

- nrf_wifi/fw_if/umac_if/src/tx.c
A recent fix to update error statistics covered the txbuffer done process in an if-else check. This prevents tx buffers from being released on tx failure. place the status check to only update error statistics and remove txdone API from if check.
> nrf_wifi: Fix a buffer free issue for raw tx packet transmit done

- nrf_wifi/hw_if/hal/src/hal_api.c
If MCU isn't ready in 1s then there is not much use in waiting longer, so, decrease the timeout to 1s and also rejig the code to make it readable.
Fixes SHEL-2480 partially.
> nrf_wifi: Decrease MCU boot timeout

- nrf_wifi/fw_if/umac_if/src/tx.c
This change fixes issue SHEL-2551
> nrf_wifi: Fix issue SHEL-2551

- nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
- nrf_wifi/fw_if/umac_if/src/radio_test/fmac_api.c
[SHEL-2533]: The problem of TX output power disparity has been resolved, which occurs when the default power is set without utilizing the TX power command, and the power is explicitly set using the TX power command through the Radio test application.
[SHEL-2533]: https://nordicsemi.atlassian.net/browse/SHEL-2533?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> nrf_wi: Fix TX power issue

- nrf_wifi/fw_if/umac_if/src/fmac_util.c
- nrf_wifi/fw_if/umac_if/src/rx.c
If operating mode is set to station with promiscuous sub-mode enabled, the interface type check for BSSID for recieve address mapping in the transmit path is missed. This causes a wdevID of 255 to be sent to UMAC causing a UMAC crash.
Also, CONFIG check for sniffer callback is missed and added.
Fixes SHEL-2564
> nrf_wifi: Fix the receive address API to get proper BSSID

- nrf_modem/doc/api.rst
- nrf_modem/doc/fault_handling.rst
- nrf_modem/doc/sockets/rai.rst
- nrf_modem/doc/sockets/socket_options_func.rst
Clean up function references.
Add nrf_accept and nrf_setdnsaddr to list of supported functions.
Signed-off-by: Andreas Moltumyr <andreas.moltumyr@nordicsemi.no>
> nrf_modem: doc: cleanup function references

- nrf_wifi/fw_if/umac_if/inc/fmac_api_common.h
In the monitor mode support defined is missing.
Add defined into condition.
> nrf_wifi: Fix defined in monitor mode support

- CODEOWNERS
Without this entry, the default entry is being used which doesn't have RPU owners.
> nrf_wifi: Fix codeowners for FW patches

- .github/test-spec.yml
Add CI-ble-samples-test label and test spec for ble sample CI. It has different test scope than BLE CI
> test-spec: introduce specific ble-sample label

- mpsl/Kconfig
nRF54H20 PDK is superseded by nRF54H20 DK and will no longer be supported, so instead of the SOC_NRF54H20_ENGA_CPURAD option that no longer exists, SOC_NRF54H20_CPURAD needs to be used.
> mpsl: Kconfig: Replace nRF54H20 PDK with DK

- .github/workflows/manifest-PR.yml
This action will create manifest PR automatically for every PR that gets created into this repo.
> ci: add workflow to create manifest PRs

- nrf_802154/driver/src/mac_features/nrf_802154_csma_ca.c
- nrf_802154/driver/src/nrf_802154.c
- nrf_802154/driver/src/nrf_802154_core.c
- nrf_802154/driver/src/nrf_802154_trx.c
- nrf_802154/driver/src/nrf_802154_trx.h
- nrf_802154/driver/src/nrf_802154_tx_power.c
- nrf_802154/driver/src/nrf_802154_tx_power.h
- nrf_802154/driver/src/nrf_802154_types_internal.h
- nrf_802154/sl/include/nrf_802154_fal.h
- nrf_802154/sl/sl_opensource/src/nrf_802154_sl_fem.c
This PR updates revision of the nrf_802154 component to commit
ee38cef4fd93ed2807f16580754057e3943ab1f5 of the sdk-nrf-802154
repository.
> nrf_802154: Update revision of nrf_802154

- nrf_wifi/fw_if/umac_if/src/cmd.c
Send the user configured timeout down to RPU.
Implements SHEL-2689.
> nrf_wifi: Configure the AP dead detection timeout

- nrf_wifi/fw_if/umac_if/src/cmd.c
The 'WIFI' is missing in the name of DFS channel
kconfig option. So it was not enabling the DISABLE_DFS_CHANNELS flag.
> nrf_wifi: Fix name of DFS channel kconfig option

- mpsl/CMakeLists.txt
- mpsl/Kconfig
- mpsl/fem/CMakeLists.txt
- softdevice_controller/CMakeLists.txt
Instead of using SOC and ARCH configs to determine the library paths, use mpsl-specific kconfigs. We will then be able to change the paths independently of which value various upstream configs have.
This also makes it simpler to use the same library for different socs, or different libraries for the same cpu core variant.
> mpsl: Use kconfig to determine library path

- .github/workflows/manifest-PR.yml
This commit will ensure that manifest-PRs generated from nrfxlib-PRs will contain the nrfxlib-PR title in the manifest-PR.
This will make it easier to browse through manifest-PRs in sdk-nrf.
> ci: Manifest-PR action to add sub-PR title to manifest PR

- nrf_modem/doc/api.rst
Add ref label for AGNSS data type enum API
This helps to fix the link in [PR 14859](https://github.com/nrfconnect/sdk-nrf/pull/14859/files#diff-478a3860a34e7a4faf66f620bee86e14a1fd4b71e4e179908370313fa5703506R135).
> doc: Add ref label for AGNSS data type enum API

- nrf_rpc/README.rst
- nrf_rpc/doc/protocol_specification.rst
Add initial version of the nRF RPC protocol specification that describes the nRF RPC packet format.
> nrf_rpc: Add initial protocol specification

- doc/links.txt
- zboss/doc/zboss_certification.rst
Replace Zigbee related Infocenter links by corresponding TechDocs ones.
> doc: zigbee: update Infocenter links

- lc3/Kconfig
Add a dependency on `SW_CODEC_LC3_T2_SOFTWARE` for all the sub-options. This prevents every `default y` symbol from appearing in `autoconf.h` when this module is not used.
> lc3: add dependency to symbols

- nrf_wifi/fw_if/umac_if/src/tx.c
In case if RPU is in TWT sleep state and transmission is blocked, the non-emergency packet is dequeued and then not re-queued leading to packet leak.
Use peek instead of de-queue.
> nrf_wifi: Fix packet leak during TWT sleep

- nrf_wifi/bus_if/bus/qspi/src/qspi.c
- nrf_wifi/bus_if/bus/spi/src/spi.c
- nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
- nrf_wifi/hw_if/hal/src/hal_api.c
If interface is de-initialized during active traffic, then the HAL RX lock still doesn't protect the full de-initialization path, there is a race after TX de-init, lock is released and before the FMAC context is de-initialized the NULL checks elsewhere pass and can lead to crashes.
Add an atomic API that does both de-initialization and removal by taking the HAL RX lock for both operations, this way FMAC context is freed and NULL checks should avoid any crashes.
Fixes SHEL-2436.
> nrf_wifi: Fix TX de-init crash

- nrf_wifi/fw_if/umac_if/src/default/fmac_api.c
When sniffer packet length is attempted to be set by the application, it is possible that the filter setting from the upper layer might come in as zero. In such a scenario, set the previously configured filter setting to the lower layer.
Additional fix for SHEL-2790
> nrf_wifi: Set appropriate filter setting for packet length

- nrf_modem/Kconfig
Add an explicit default, to ease integration with a private repository.
> nrf_modem: add an explicit default for which binary is linked

- nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
- nrf_wifi/fw_if/umac_if/src/cmd.c
[SHEL-2947] Option to set either PS-poll or QoS null frame based power save data retrieval mechanism.
[SHEL-2947]: https://nordicsemi.atlassian.net/browse/SHEL-2947?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> nrf_wifi: Option for power save data retrieval

- mpsl/Kconfig
The nonsecure board variant needs different libraries that are built for nonsecure.
> mpsl: Choose nonsecure libraries if building for nonsecure variant

- nrf_wifi/fw_if/umac_if/inc/fw/host_rpu_sys_if.h
- nrf_wifi/fw_if/umac_if/inc/radio_test/fmac_api.h
- nrf_wifi/fw_if/umac_if/inc/radio_test/fmac_structs.h
- nrf_wifi/fw_if/umac_if/src/event.c
- nrf_wifi/fw_if/umac_if/src/radio_test/fmac_api.c
- nrf_wifi/hw_if/hal/inc/fw/phy_rf_params.h
[SHEL-2811]: Added command to get user-specified timeout in seconds.Rx samples will be displayed only when the capture occurs before the timeout lapses.
[SHEL-2811]: https://nordicsemi.atlassian.net/browse/SHEL-2811?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> wifi: radio_test: Add timeout parameter for capture mode

- nrf_802154/common/include/nrf_802154_types.h
- nrf_802154/doc/CHANGELOG.rst
- nrf_802154/driver/src/nrf_802154_aes_ccm_acc_ccm.c
- nrf_802154/driver/src/nrf_802154_core.c
- nrf_802154/driver/src/nrf_802154_peripherals_nrf53.h
- nrf_802154/driver/src/nrf_802154_peripherals_nrf54h.h
- nrf_802154/driver/src/nrf_802154_peripherals_nrf54l.h
- nrf_802154/driver/src/nrf_802154_trx_dppi.c
This PR updates revision of the nrf_802154 component to commit
b63820437291962aa0d5d0f90578e866ac04a11b of the sdk-nrf-802154
repository.
> Update revision of nrf_802154

- openthread/cmake/extensions.cmake
Add soft float fallback to enable building from libs with softfp ABI enabled.
Code built with `soft` and `softfp` `float-abi` options can be linked together as they both use the same soft-float ABI and generate functions to pass floating-point arguments to integer registers. This is contrary to the `hard` option where floating-point arguments are passed directly to FPU registers. `softfp` additionally allows using hardware floating-point instructions instead of emulated ones.
> openthread: add soft float fallback for lib path calculation

- common.cmake
- nrf_802154/sl/sl/CMakeLists.txt
For builds with Kconfig option `CONFIG_TRUSTED_EXECUTION_NONSECURE` the non-secure binaries of nRF 802.15.4 SL library must be used.
To allow this with current `nrfxlib_calculate_lib_path` cmake function, the function is given additional parameter NS_PROVIDED.
This approach does not force other users to provide non-secure versions of their libraries (for example if their libs are secure-agnostic).
The nrfxlib_calculate_lib_path adds `_ns` suffix to the returned library path when the SoC is nRF54L15 and `CONFIG_TRUSTED_EXECUTION_NONSECURE` is enabled.
Other SoCs are out of scope now.
The nRF 802.15.4 SL library for nRF54L non-secure is deployed already with the PR:
https://github.com/nrfconnect/sdk-nrfxlib/pull/1430
> nrf_802154: nRF54L15 use non-secure SL library for builds with `CONFIG_TRUSTED_EXECUTION_NONSECURE`

- doc/links.txt
- nrf_modem/doc/dectphy.rst
Added nRF9151 dect NR+ link
in the nrf_modem lib docs.
> doc: Add nRF9151 DECT NR+ link

- openthread/CMakeLists.txt
- openthread/Kconfig
- openthread/cmake/extensions.cmake
Added NRFXLIB_RELEASE_TAG to the configuration file to save information for which release tag the libraries have been generated.
manfiest-PR-skip
> openthread: Added nrfxlib release tag to CMAKE function

- nrf_rpc/CHANGELOG.rst
- nrf_rpc/nrf_rpc_cbor.c
The zcbor's stop_on_error flag, which defaults to false, makes the decoder stop decoding any subsequent items after a decoding error occurs, meaning that all subsequent decoding attempts fail early until the error is cleared with zcbor_pop_error() function.
This flag is already set for the encoder yet it was omitted for the decoder although some nRF RPC decoder functions seem to rely the flag being set as they only check the decoding result after trying to decode all the command or response arguments.
> nrf_rpc: enable zcbor stop_on_error flag for decoding

- crypto/doc/api.rst
- gzll/doc/api.rst
- lc3/doc/api.rst
- mpsl/doc/api.rst
- nfc/doc/type_2_tag.rst
- nfc/doc/type_4_tag.rst
- nrf_802154/doc/api.rst
- nrf_dm/doc/api.rst
- nrf_fuel_gauge/doc/api.rst
- nrf_modem/doc/api.rst
- nrf_rpc/doc/api.rst
- nrf_wifi/doc/API/fmac/low_api_common.rst
- nrf_wifi/doc/API/fmac/low_api_radio_test.rst
- nrf_wifi/doc/API/fmac/low_api_wifi.rst
- nrf_wifi/doc/API/fw_if.rst
- softdevice_controller/doc/api.rst
Doxybridge does not support any attributes, so let's drop them all.
> doc: remove unsupported doxygen directive attributes

- nrf_rpc/include/nrf_rpc.h
- nrf_rpc/nrf_rpc_cbor.c
According to documentation `nrfxlib/nrf_rpc/README.rst` NRF RPC should be OS independent so this commit removes `BIT` and `ARRAY_SIZE` macros that are take directly form zephyr.
> nrf_rpc: Fix OS dependencies in NRF RPC.

- nrf_rpc/nrf_rpc.c
Commit removes any data sending over serial transport from rx thread and adds sending over allocated pool of threads for incoming data execution.
The reason of this: if sending requires some acknowledgements then deadlock of rx thread happens.
> nrf_rpc: remove sending from rx thread

- .github/workflows/compliance.yml
Required due to Zephyr upstream changes.
Same change that was done for sdk-nrf:
https://github.com/nrfconnect/sdk-nrf/commit/3c7c249dd409bfb415f25336a7b15eff6871c534
> workflows: add unidiff for compliance workflow

- CODEOWNERS
> zboss: transfer ownership to `ncs-zigbee`

- zboss/Kconfig
Make sure all choices under `ZIGBEE` have a name.
> zboss: name some unnamed Kconfig options

- doc/links.txt
Updated the link for the Bluetooth Core Specification so that it points to the 6.0 revision instead of the 5.4
> doc: Updated Bluetooth Core Spec Link

- softdevice_controller/CHANGELOG.rst
Updates the NCS release version in the CHANGELOG to match with the tag
> SoftDevice Controller: Use correct NCS release tag

- mpsl/Kconfig
> mpsl: Enable on nRF54H20 EngB

- mpsl/Kconfig
Backport 1e25b050dc4cfc767ced5f75174460d67b19b688 from #1528.
> [Backport v2.8-branch] mpsl: Enable on nRF54H20 EngB

- nrf_rpc/nrf_rpc.c
Commit fixes null dereference when error handling
is triggered but group does not exist.
> nrf_rpc: fix error handling

- doc/links.txt
- mpsl/CHANGELOG.rst
- nrf_802154/doc/CHANGELOG.rst
- nrf_fuel_gauge/CHANGELOG.rst
- nrf_modem/doc/CHANGELOG.rst
- nrf_rpc/CHANGELOG.rst
- softdevice_controller/CHANGELOG.rst
Backport b847547bea60d5e0cd2096e291bb8ca784393da1 from #1567.
> [Backport v2.8-branch] doc: Update doc versions in nrfxlib for 2.8.0

- nrf_rpc/nrf_rpc.c
1. Ensure that the group's bound_handler is called after sending the init reply. This is to make sure that the remote knows our group ID and is able to process incoming commands when the handler is called.
2. Similarly, signal groups_init_event after sending the init reply.
---
nrf_rpc: refactor internal tasks
1. Rename internal_data to internal_task to better describe the purpose of the structure.
2. Use internal_task_consumed event to notify about freeing the global task object for all types of tasks.
3. Use union for different types of tasks to not bloat the internal task structure when more tasks or fields are added.
> nrf_rpc: call bound_handler after init reply

- nrf_rpc/nrf_rpc.c
- nrf_rpc/template/nrf_rpc_os_tmpl.h
Fix possible data race that may happen when the transport receives the first nRF RPC packet before the thread that initializes nRF RPC marks the group's transport as initialized.
Also, clean up the OS layer template.
> nrf_rpc: fix possible data race at initialization

- nrf_modem/doc/at_interface.rst
- nrf_modem/doc/gnss_interface.rst
Minor fixes to the following pages:
* nrf_modem/doc/at_interface.rst
* nrf_modem/doc/gnss_interface.rst - nrf_modem_gnss_system_mask_set is renamed to nrf_modem_gnss_signal_mask_set.
TECHDOC-3122 and TECHDOC-3107
> doc: Minor updates to Modem library

- nrf_rpc/include/nrf_rpc.h
- nrf_rpc/nrf_rpc.c
Add nrf_rpc_set_bound_handler() that allows to register a global handler that is called when the remote binds to a local nRF RPC group (either for the first time, or after a reboot.
> nrf_rpc: detect reboot of the remote

- .github/workflows/dnm.yml
This aligns with other repositories in NCS.
> workflows: Add workflow to prevent merging PRs with DNM label

- mpsl/doc/cx.rst
- nfc/CHANGELOG.rst
- nrf_802154/doc/CHANGELOG.rst
- nrf_modem/doc/CHANGELOG.rst
- nrf_rpc/CHANGELOG.rst
Backport e1c5c7d3765829b6474da35c5b9f0986e07022e7 from #1610.
> [Backport v2.9-branch] doc: Documentation check for 2.9

- nrf_802154/doc/rd_limitations.rst
The nrf/samples/nrf5340/multiprotocol_rpmsg sample is removed. References to it in historical files are changed to text ``nRF5340: Multiprotocol RPMsg``.
> doc: remove references to removed sample `nRF5340: Multiprotocol RPMsg`

- .github/workflows/compliance.yml
ubuntu-latest points to 24.04 - use 22.04 instead   
> ci: fix compliance by using ubuntu-22.04

- nrf_modem/doc/gnss_interface.rst
Changed GNSS interface name in documentation from `Global Satellite Navigation System` to `GNSS`. The name of the interface in modemlib is `GNSS` and in general all documentation refers to `GNSS interface` or `GNSS API`.
> nrf_modem: doc: Change GNSS interface name

- nrf_modem/include/nrf_modem.h
`NRF_ENOTSUPP` is not a valid NRF error code. Change to presumed `NRF_ENOTSUP` (unless it was meant to be `NRF_EOPNOTSUPP`? No way of checking since it's a binary)
> nrf_modem: Fix typo in return values in nrf_modem.h

- nrf_rpc/include/nrf_rpc.h
- nrf_rpc/nrf_rpc.c
In C++, conversion from a function pointer to void* is either undefined (prior to C++11) or not implicit.
Move the static inline functions to the C file for better portability. The flash impact imposed by this is negligible.
> nrf_rpc: fix build error for C++

- .github/workflows/compliance.yml
The actions/cache@v1 is deprecated. Update to actions/cache@v4.
> ci: fix compliance by updating actions/cache

- common.cmake
Adds case in nrfxlib_calculate_lib_path for nrf54l09. Both secure and non-secure variants lib paths will be calculated.
> cmake: add nrfxlib_calculate_lib_path case for nrf54l09

- .github/workflows/compliance.yml
- nrf_wifi/fw_if/umac_if/inc/fmac_structs_common.h
- nrf_wifi/fw_if/umac_if/src/fmac_api_common.c
Fixes a leak in regulatory processing.
> wifi: Fix memleak in regulatory processing 

- .github/test-spec.yml
Sidewalk becomes NCS Add-on.
There is no need to trigger Sidewalk tests.
> ci: remove Sidewalk from test-spec

- nrf_802154/driver/src/mac_features/nrf_802154_delayed_trx.c
When compiling with clang, then unneeded extra parentheses triggers the warning:
> ...nrf_802154/driver/src/mac_features/nrf_802154_delayed_trx.c:187:32:
>           warning: equality comparison with extraneous parentheses
>           [-Wparentheses-equality]
>   187 |             if ((p_dly_op_data == NULL))
>       |                  ~~~~~~~~~~~~~~^~~~~~~
> 1 warning generated.
> nrf_802154: remove extraneous parentheses as those are not needed

- nrf_802154/driver/src/mac_features/nrf_802154_delayed_trx.c
Backport 864943e7301aa90eb684829f10905e910e844f18 from #1715.
> [Backport v3.0-branch] nrf_802154: remove extraneous parentheses as those are not needed

- nrf_802154/doc/CHANGELOG.rst
- nrf_802154/driver/src/nrf_802154_trx.c
Backport db0d437be415b42a3b55aa32fb91d4ba883c4909 from #1726.
> [Backport v3.0-branch] Update revision of nrf_802154

- nfc/CHANGELOG.rst
- nrf_802154/doc/CHANGELOG.rst
- nrf_fuel_gauge/CHANGELOG.rst
- nrf_modem/doc/CHANGELOG.rst
- softperipheral/CHANGELOG.rst
Backport 5936aa15ddceaeed703c9adebb831c6d740fa8d8 from #1723.
> [Backport v3.0-branch] doc: Update doc versions in nrfxlib for 3.0.0

- nrf_rpc/nrf_rpc.c
Since the NRF_RPC_ASSERT macro is not enabled, clang complains about the function being unused.
> nrf_rpc: Declare packet_validate as unused

- common.cmake
Updates the cmake defines used to calculate the path with the naming change.
> cmake: update nrfxlib_calculate_lib_path case for nrf54lm20a and nrf54lv10a

- nrf_rpc/include/nrf_rpc_cbor.h
- nrf_rpc/nrf_rpc_cbor.c
Optimize _nrf_rpc_cbor_decoder structure size by removing unused decoding_done_required member. This saves 4B of flash per command decoder.
> nrf_rpc: remove decoding_done_required

- gzll/doc/integration_notes.rst
- nrf_modem/doc/CHANGELOG.rst
- nrf_modem/doc/sockets/socket_options_func.rst
- softdevice_controller/CHANGELOG.rst
- softdevice_controller/doc/scheduling.rst
- softperipheral/doc/introduction.rst
Updated nrfxlib docs for VALE.
> doc: Updated nrfxlib docs for VALE

- mpsl/Kconfig
The folder name has changed.
Jira-ref: DRGN-21945.
> mpsl: Update default location for bsim libraries

- nfc/Kconfig
Aligned the availability of the NFC_T2T_NRFXLIB and NFC_T4T_NRFXLIB Kconfig options with the status of the nfct DTS node.
> nfc: align the T2T and T4T Kconfig options with DTS node status

- nrf_802154/doc/multiprotocol_support.rst
- nrf_802154/doc/multiprotocol_switching_tables.rst
Backport 3567254c1693f05af73bee03a17fbca04b42b2ce from #1820.
> [Backport v3.1-branch] Update revision of nrf_802154

- mpsl/CHANGELOG.rst
- nrf_802154/doc/CHANGELOG.rst
- nrf_802154/doc/rd_service_layer_lib.rst
- nrf_modem/doc/CHANGELOG.rst
- nrf_rpc/CHANGELOG.rst
- softdevice_controller/CHANGELOG.rst
- softperipheral/doc/sQSPI/features.rst
- softperipheral/doc/sQSPI/nrf54H20_porting_v1_1_0.rst
- softperipheral/doc/sQSPI/nrf54L15_porting_v1_1_0.rst
Backport 390e818f6ddf400b78862efc2205ecc59191055d from #1826.
> [Backport v3.1-branch] doc: Update doc versions in nrfxlib for 3.1.0

- nfc/README.rst
Update docs to the new names of nfc tag libraries
JIRA: NCSDK-35486
> doc: nfc: Fixed lib names
